import os
import json
import re
from dotenv import load_dotenv
import google.generativeai as genai
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma
from collections import defaultdict

# Load environment variables from .env file
load_dotenv()
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# Configure Gemini API (needed for embeddings if Chroma needs to re-initialize it)
genai.configure(api_key=GOOGLE_API_KEY)

# --- Configuration ---
# The directory where your vector database is saved.
CHROMA_DB_DIR = "chroma_db_langchain"

# The path where the final JavaScript data file will be saved.
# Adjust this path to point to your React app's 'src' folder.
OUTPUT_PATH = "../fundile-tlassistant-vite/src/curriculumData.js" 

def create_curriculum_data_file_from_chroma():
    """
    Loads curriculum metadata from the Chroma vector database and generates
    a single JavaScript data file for the frontend, extracting topics
    from Textbook and StudyGuide document metadata.
    Updated: Now correctly processes Syllabus documents for individual grades.
    """
    print("Starting curriculum data build process from ChromaDB...")
    
    # Initialize embeddings (must match what was used for ingestion)
    embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001", google_api_key=GOOGLE_API_KEY)

    try:
        # Load the existing Chroma vector database
        vectorstore = Chroma(
            persist_directory=CHROMA_DB_DIR,
            embedding_function=embeddings,
            collection_name="caps_curriculum_collection"
        )
        
        all_db_documents = vectorstore._collection.get(include=['metadatas'])
        
        if not all_db_documents or not all_db_documents.get('metadatas'):
            print("\nWarning: No documents found in ChromaDB or no metadata available. The output file will be empty.")
            return

        # Use defaultdict for easier nesting: subject -> grade -> list of topics/syllabus info
        curriculum_data = defaultdict(lambda: defaultdict(lambda: {'topics': [], 'syllabus_info': None}))

        # Iterate through all document metadatas to extract curriculum structure
        for metadata in all_db_documents['metadatas']:
            doc_type = metadata.get('document_type')
            subject = metadata.get('subject')
            grade = metadata.get('grade') # This will be a single grade for Textbook/StudyGuide/Syllabus/Exam

            if subject and grade:
                # Add topics from Textbook Chapters and Study Guides
                if doc_type in ['Textbook Chapter', 'Study Guide'] and metadata.get('topic'):
                    topic_name = metadata['topic']
                    if topic_name not in curriculum_data[subject][grade]['topics']:
                        curriculum_data[subject][grade]['topics'].append(topic_name)
                
                # Add syllabus information (assuming one syllabus per subject/grade)
                elif doc_type == 'Syllabus':
                    # For syllabus, we might store a reference or a flag that it exists
                    # For now, let's just mark that a syllabus exists for this subject/grade
                    curriculum_data[subject][grade]['syllabus_info'] = True 
                    # If you need more details from the syllabus, like a summary,
                    # that would need to be extracted during RAG ingestion and stored in metadata.

        # Convert defaultdicts back to regular dicts for JSON serialization
        final_curriculum_data = {}
        for subject, grades_data in curriculum_data.items():
            final_curriculum_data[subject] = {}
            for grade, data in grades_data.items():
                # Sort topics alphabetically for consistent display
                data['topics'] = sorted(list(set(data['topics']))) # Ensure uniqueness and sort
                final_curriculum_data[subject][grade] = data # Store both topics and syllabus_info

        if not final_curriculum_data:
            print("\nWarning: No relevant Textbook, StudyGuide, or Syllabus documents found in ChromaDB metadata. The output file will be empty.")
            return

        # Ensure the output directory exists
        output_dir = os.path.dirname(OUTPUT_PATH)
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            print(f"Created output directory: {output_dir}")

        # Convert the Python dictionary to a JSON string for writing to the file
        json_string = json.dumps(final_curriculum_data, indent=4)

        # Write the data to the JavaScript file, exporting it as a constant
        with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
            f.write("// This file is auto-generated by the build_curriculum_data.py script.\n")
            f.write("// Do not edit this file manually.\n\n")
            f.write("export const curriculumData = ")
            f.write(json_string)
            f.write(";")

        print(f"\nSuccess! Curriculum data has been written to: {OUTPUT_PATH}")

    except Exception as e:
        print(f"\nAn unexpected error occurred: {e}")
        print(f"Please ensure your ChromaDB directory '{CHROMA_DB_DIR}' exists and contains data.")

if __name__ == "__main__":
    # Before running, ensure you have run RAG Ingestion.txt to populate ChromaDB.
    create_curriculum_data_file_from_chroma()

