from __future__ import annotations

from typing import Any, Dict, List


def build_pools_by_subskill(
    *,
    concepts_pool: List[Dict[str, Any]],
    equation_pool: List[Dict[str, Any]],
    ledger_pool: List[Dict[str, Any]],
    general_ledger_pool: List[Dict[str, Any]],
    debtors_ledger_pool: List[Dict[str, Any]],
    creditors_ledger_pool: List[Dict[str, Any]],
    trial_balance_pool: List[Dict[str, Any]],
    trading_stock_account_pool: List[Dict[str, Any]],
    full_accounting_cycle_bookkeeping_pool: List[Dict[str, Any]],
    control_accounts_pool: List[Dict[str, Any]],
    control_accounts_reconciliation_pool: List[Dict[str, Any]],
    reconciliation_analysis_pool: List[Dict[str, Any]],
    journals_pool: List[Dict[str, Any]],
    crj_pool: List[Dict[str, Any]],
    cpj_pool: List[Dict[str, Any]],
    dj_pool: List[Dict[str, Any]],
    daj_pool: List[Dict[str, Any]],
    cj_pool: List[Dict[str, Any]],
    caj_pool: List[Dict[str, Any]],
    pcj_pool: List[Dict[str, Any]],
    gj_pool: List[Dict[str, Any]],
    mixed_pool: List[Dict[str, Any]],
) -> Dict[str, List[Dict[str, Any]]]:
    return {
        "concepts": concepts_pool,
        "definition": concepts_pool,
        "equation": equation_pool,
        "accounting equation": equation_pool,
        "ledgers": ledger_pool,
        "ledger": ledger_pool,
        "general_ledger": general_ledger_pool,
        "debtors_ledger": debtors_ledger_pool,
        "creditors_ledger": creditors_ledger_pool,
        "trial_balance": trial_balance_pool,
        "trial balance": trial_balance_pool,
        "trading_stock_account": trading_stock_account_pool,
        "trading stock account": trading_stock_account_pool,
        "full_accounting_cycle_bookkeeping": full_accounting_cycle_bookkeeping_pool,
        "control_accounts": control_accounts_pool,
        "control_accounts_reconciliation": control_accounts_reconciliation_pool,
        "reconciliation_analysis": reconciliation_analysis_pool,
        "journals": journals_pool,
        "journal": journals_pool,
        "crj": crj_pool,
        "cpj": cpj_pool,
        "dj": dj_pool,
        "daj": daj_pool,
        "cj": cj_pool,
        "caj": caj_pool,
        "pcj": pcj_pool,
        "gj": gj_pool,
        "mixed": mixed_pool,
    }
