"""Topic alias mapping table for curriculum generators."""
from typing import Dict

TOPIC_ALIASES: Dict[str, str] = {
    "waves sound and light": "grade10_physical_sciences_waves_sound_light",
    "waves": "grade10_physical_sciences_waves_sound_light",
    "matter and materials": "grade10_physical_sciences_matter_materials",
    "matter": "grade10_physical_sciences_matter_materials",
    "vectors and newtons laws": "grade11_physical_sciences_vectors_newton",
    "vectors": "grade11_physical_sciences_vectors_newton",
    "vertical projectile motion": "grade12_physical_sciences_vertical_projectile",
    "vertical projectile": "grade12_physical_sciences_vertical_projectile",
    "doppler effect": "grade12_physical_sciences_doppler_effect",
    "doppler": "grade12_physical_sciences_doppler_effect",
    "meiosis": "life_sciences_meiosis_human_reproduction",
    "human reproduction": "life_sciences_meiosis_human_reproduction",

    # Foundational Math (Tang & Stokke) aliases
    "number bonds": "foundational_math_number_bonds",
    "fractions foundation": "foundational_math_number_bonds",
    "foundational math": "foundational_math_number_bonds",
    "foundational number bonds": "foundational_math_number_bonds",
    "stokke speed sprint": "foundational_math_number_bonds",
    "tang number bonds": "foundational_math_number_bonds",
    # Grade 9 Math aliases
    "factorisation": "grade9_math_factorisation",
    "algebraic fractions": "grade9_math_algebraic_fractions",
    "congruence and similarity": "grade9_math_congruence_similarity",
    "congruence": "grade9_math_congruence_similarity",
    "similarity": "grade9_math_congruence_similarity",
    # Grade 10 Math aliases
    "algebraic expressions": "grade10_math_algebraic_expressions",
    "equations & inequalities": "grade10_math_equations_inequalities",
    "equations and inequalities": "grade10_math_equations_inequalities",
    "exponents & surds": "grade10_math_exponents",
    "exponents": "grade10_math_exponents",
    "number patterns": "grade10_math_patterns_sequences",
    "patterns & sequences": "grade10_math_patterns_sequences",
    "trigonometry ratios": "grade10_math_trigonometry",
    "trigonometry": "grade10_math_trigonometry",
    "functions & graphs": "grade10_math_functions",
    "functions": "grade10_math_functions",
    "analytical geometry": "grade10_math_analytical_geometry",
    "circle & euclidean geometry": "grade10_math_euclidean_geometry",
    "euclidean geometry": "grade10_math_euclidean_geometry",
    "measurements": "grade10_math_measurements",
    "circle geometry": "grade11_math_circle_geometry",
    # Grade 11 Math aliases
    "measurement": "grade11_math_measurement",
    "linear programming": "grade11_math_linear_programming",
    "investigation and projects": "grade11_math_investigation_and_projects",
    "equations": "grade11_math_equations_inequalities",
    "surds": "grade11_math_exponents_surds",
    "circle geometry riders": "grade11_math_circle_geometry_theorems",
    "circle geometry theorems": "grade11_math_circle_geometry_theorems",
    "trigonometry reductions": "grade11_math_trigonometry_reductions",
    "trig reductions": "grade11_math_trigonometry_reductions",
    "trigonometric reductions": "grade11_math_trigonometry_reductions",
    "finance growth and decay": "grade11_math_finance_growth_decay",
    "finance growth decay": "grade11_math_finance_growth_decay",
    "finance, growth and decay": "grade11_math_finance_growth_decay",
    "grade 11 finance": "grade11_math_finance_growth_decay",
    "depreciation": "grade11_math_finance_growth_decay",
    "reducing balance": "grade11_math_finance_growth_decay",
    "nominal and effective rate": "grade11_math_finance_growth_decay",
    "nominal to effective": "grade11_math_finance_growth_decay",
    "effective rate": "grade11_math_finance_growth_decay",
    "probability contingency": "grade11_math_probability_contingency",
    "probability contingency tables": "grade11_math_probability_contingency",
    "grade 11 probability": "grade11_math_probability_contingency",
    "contingency tables": "grade11_math_probability_contingency",
    "contingency table": "grade11_math_probability_contingency",
    "two-way contingency tables": "grade11_math_probability_contingency",
    "two-way tables": "grade11_math_probability_contingency",
    "independent events": "grade11_math_probability_contingency",
    "mutually exclusive events": "grade11_math_probability_contingency",
    "statistics summary ogive": "grade11_math_statistics_summary_ogive",
    "grade 11 statistics": "grade11_math_statistics_summary_ogive",
    "ogive": "grade11_math_statistics_summary_ogive",
    "ogive curve": "grade11_math_statistics_summary_ogive",
    "five-number summary": "grade11_math_statistics_summary_ogive",
    "box and whisker": "grade11_math_statistics_summary_ogive",
    "box-and-whisker": "grade11_math_statistics_summary_ogive",
    "outliers": "grade11_math_statistics_summary_ogive",
    "skewness": "grade11_math_statistics_summary_ogive",
    # Grade 12 Math aliases
    "financial mathematics": "grade12_math_finance",
    "finance": "grade12_math_finance",
    "sequences & series": "grade12_math_patterns_sequences_series",
    "analytical trigonometry": "grade12_math_trigonometry",
    "differential calculus": "grade12_math_differential_calculus",
    "calculus": "grade12_math_differential_calculus",
    "analytical geometry circles": "grade12_math_analytical_geometry_circles",
    "circles analytical geometry": "grade12_math_analytical_geometry_circles",
    "circles": "grade12_math_analytical_geometry_circles",
    "counting principles": "grade12_math_counting_probability",
    "fundamental counting principle": "grade12_math_counting_probability",
    "counting and probability": "grade12_math_counting_probability",
    "probability": "grade12_math_counting_probability",
    "venn diagrams": "grade12_math_counting_probability",
    "permutations": "grade12_math_counting_probability",
    "bivariate statistics": "grade12_math_bivariate_statistics",
    "statistics": "grade12_math_bivariate_statistics",
    "regression": "grade12_math_bivariate_statistics",
    "least squares regression": "grade12_math_bivariate_statistics",
    "least squares": "grade12_math_bivariate_statistics",
    "correlation coefficient": "grade12_math_bivariate_statistics",
    "scatter plots": "grade12_math_bivariate_statistics",
    # Accounting aliases
    "sole trader": "grade10_accounting_sole_trader",
    "cash receipts journal": "grade10_accounting_sole_trader",
    "cash receipts journal (crj)": "grade10_accounting_sole_trader",
    "crj": "grade10_accounting_sole_trader",
    "cash payments journal": "grade10_accounting_sole_trader",
    "cash payments journal (cpj)": "grade10_accounting_sole_trader",
    "cpj": "grade10_accounting_sole_trader",
    "cash receipts & payments journals": "grade10_accounting_sole_trader",
    "debtors journal": "grade10_accounting_sole_trader",
    "debtors allowances journal": "grade10_accounting_sole_trader",
    "creditors journal": "grade10_accounting_sole_trader",
    "creditors allowances journal": "grade10_accounting_sole_trader",
    "gaap": "grade10_accounting_gaap",
    "ethics": "grade10_accounting_ethics",
    "internal control": "grade10_accounting_internal_control",
    "vat": "grade10_accounting_vat",
    "salaries & wages": "grade10_accounting_salaries_wages",
    "final accounts": "grade10_accounting_final_accounts",
    "bank reconciliation": "grade10_accounting_bank_reconciliation",
    "fixed assets": "grade11_accounting_fixed_assets",
    "income statement": "grade11_accounting_income_statement",
    "partnerships": "grade11_accounting_partnerships",
    "partnerships financial statements": "grade11_accounting_partnerships_financial_statements",
    "partnership financial statements": "grade11_accounting_partnerships_financial_statements",
    "appropriation account": "grade11_accounting_partnerships_financial_statements",
    "current accounts note": "grade11_accounting_partnerships_financial_statements",
    "current account note": "grade11_accounting_partnerships_financial_statements",
    "inventory valuation": "grade11_accounting_inventory_valuation",
    "inventory systems": "grade11_accounting_inventory_valuation",
    "fifo": "grade11_accounting_inventory_valuation",
    "weighted average": "grade11_accounting_inventory_valuation",
    "fifo and weighted average": "grade11_accounting_inventory_valuation",
    "cash flow": "grade12_accounting_cash_flow_statement",
    "cash flow statement": "grade12_accounting_cash_flow_statement",
    "cash flow statements": "grade12_accounting_cash_flow_statement",
    "cash generated from operations": "grade12_accounting_cash_flow_statement",
    "taxation paid": "grade12_accounting_cash_flow_statement",
    "dividends paid": "grade12_accounting_cash_flow_statement",
    "working capital changes": "grade12_accounting_cash_flow_statement",
    "financial indicators": "grade12_accounting_financial_indicators",
    "financial ratios": "grade12_accounting_financial_indicators",
    "financial indicators & ratios": "grade12_accounting_financial_indicators",
    "analysis and interpretation": "grade12_accounting_financial_indicators",
    "analysis and interpretation of financial statements": "grade12_accounting_financial_indicators",
    "analysis of financial statements": "grade12_accounting_financial_indicators",
    "interpretation of financial statements": "grade12_accounting_financial_indicators",
    "current ratio": "grade12_accounting_financial_indicators",
    "acid test ratio": "grade12_accounting_financial_indicators",
    "acid test": "grade12_accounting_financial_indicators",
    "debtors collection period": "grade12_accounting_financial_indicators",
    "creditors payment period": "grade12_accounting_financial_indicators",
    "debt equity ratio": "grade12_accounting_financial_indicators",
    "debt to equity": "grade12_accounting_financial_indicators",
    "gearing": "grade12_accounting_financial_indicators",
    "financial risk": "grade12_accounting_financial_indicators",
    "roshe": "grade12_accounting_financial_indicators",
    "return on shareholders equity": "grade12_accounting_financial_indicators",
    "return on average shareholders equity": "grade12_accounting_financial_indicators",
    "earnings per share": "grade12_accounting_financial_indicators",
    "dividends per share": "grade12_accounting_financial_indicators",
    "eps": "grade12_accounting_financial_indicators",
    "dps": "grade12_accounting_financial_indicators",
    "cost accounting": "grade12_accounting_cost_accounting",
    "production cost statement": "grade12_accounting_cost_accounting",
    "break even analysis": "grade12_accounting_cost_accounting",
    "budgets": "grade12_accounting_budgets",
    "budgeting": "grade12_accounting_budgets",
    "cash budget variance analysis": "grade12_accounting_cash_budget_variance",
    "companies": "grade12_accounting_companies",
    "debtors age analysis": "grade12_accounting_debtors_age_analysis",
    "the accounting equation": "grade12_accounting_equation",
    "accounting equation": "grade12_accounting_equation",
    "value added tax": "grade12_accounting_vat",
    "valued added tax": "grade12_accounting_vat",
    "disposal of tangible assets": "grade11_accounting_disposal_of_tangible_assets",
    "fixed tangible assets": "grade11_accounting_fixed_tangible_assets",
    "cost accounting manufacturing": "grade12_accounting_cost_accounting",
    "reconciliations": "grade11_accounting_reconciliation",
    "calculations involving percentages": "grade12_accounting_financial_indicators",
    "preliminary information": "grade12_accounting_concepts",
    "basic concepts of accounting": "grade12_accounting_concepts",
    "accounting principles": "grade10_accounting_gaap",
    "difference between financial and managerial accounting": "grade12_accounting_concepts",
    "managing resources": "grade10_accounting_internal_control",
    "informal or indigenous bookkeeping systems": "grade10_accounting_sole_trader",
    "salaries and wages journal": "grade10_accounting_salaries_wages",
    "non profit organisations or clubs": "grade11_accounting_concepts",
    "introduction to accounting": "grade10_accounting_sole_trader",
    "inventories": "grade11_accounting_inventory_valuation",
    "control accounts": "grade11_accounting_partnership_ledger",
    "financial accounting of a sole trader": "grade10_accounting_sole_trader",
    "financial accounts and year end adjustments of a sole trader": "grade10_accounting_final_accounts",
    "financial statements of a sole trader": "grade10_accounting_final_accounts",
    "analysis and interpretation of financial statements of a sole trader": "grade10_accounting_final_accounts",
    "partnerships analysis of financial statements": "grade11_accounting_partnerships_financial_statements",
    "financial information and gaap": "grade10_accounting_gaap",
    # Business Studies aliases
    "micro environment": "grade10_bs_micro_environment",
    "market environment": "grade10_bs_market_environment",
    "macro environment": "grade10_bs_macro_environment",
    "business functions": "grade10_bs_business_functions",
    "forms of ownership": "grade10_bs_forms_of_ownership",
    "social responsibility": "grade10_bs_social_responsibility",
    "socio-economic issues": "grade10_bs_socio_economic_issues",
    "business studies essay": "grade12_bs_essay",
    "business studies section c": "grade12_bs_essay",
    "section c essay": "grade12_bs_essay",
    "impact of recent legislation on businesses": "grade12_bs_legislation_hr",
    "recent legislation": "grade12_bs_legislation_hr",
    "human resources function": "grade12_bs_legislation_hr",
    "human resources": "grade12_bs_legislation_hr",
    "investments securities": "grade12_bs_investments_management",
    "investments insurance": "grade12_bs_investments_management",
    "investments": "grade12_bs_investments_management",
    "management & leadership": "grade12_bs_investments_management",
    "management and leadership": "grade12_bs_investments_management",
    "quality of performance": "grade12_bs_investments_management",
    "marketing function": "grade11_bs_marketing_production",
    "the marketing function": "grade11_bs_marketing_production",
    "production function": "grade11_bs_marketing_production",
    "the production function": "grade11_bs_marketing_production",
    # Senior Phase Math aliases
    "theorem of pythagoras": "grade8_math_theorem_of_pythagoras",
    "pythagoras": "grade8_math_theorem_of_pythagoras",
    "geometry of 2d shapes": "grade8_math_geometry_of_2d_shapes",
    "geometry of 3d objects": "grade7_math_geometric_nets_3d",
    "geometric nets for 3d shapes": "grade7_math_geometric_nets_3d",
    "geometric nets": "grade7_math_geometric_nets_3d",
    "nets of 3d shapes": "grade7_math_geometric_nets_3d",
    "3d shapes and nets": "grade7_math_geometric_nets_3d",
    "nets for 3d shapes": "grade7_math_geometric_nets_3d",
    "3d shapes": "grade7_math_geometric_nets_3d",
    "polyhedra": "grade7_math_geometric_nets_3d",
    "geometry of straight lines": "grade8_math_geometry_of_straight_lines",
    "straight lines": "grade8_math_geometry_of_straight_lines",
    "area and perimeter of 2d shapes": "grade8_math_area_and_perimeter_of_2d_shapes",
    "area and perimeter": "grade8_math_area_and_perimeter_of_2d_shapes",
    "surface area and volume of 3d objects": "grade8_math_surface_area_and_volume_of_3d_objects",
    "surface area and volume": "grade8_math_surface_area_and_volume_of_3d_objects",
    "data handling": "grade8_math_data_handling",
    "transformation geometry": "grade8_math_transformation_geometry",
    "transformations": "grade8_math_transformation_geometry",
    "construction of geometric figures": "grade8_math_construction_of_geometric_figures",
    "constructions": "grade8_math_construction_of_geometric_figures",
    # EMS aliases
    "senior phase gap": "grade8_ems_gap",
    "savings": "grade7_ems_savings",
    "production process": "grade8_ems_gap",
    "management levels": "grade8_ems_gap",
    # Science & Tech aliases
    "mechanics": "physical_sciences_mechanics",
    "physical sciences": "physical_sciences_mechanics",
    "newton's laws": "physical_sciences_mechanics",
    "vectors": "physical_sciences_mechanics",
    "inclined planes": "physical_sciences_inclined_planes",
    "momentum and impulse": "physical_sciences_momentum_impulse",
    "momentum & impulse": "physical_sciences_momentum_impulse",
    "momentum": "physical_sciences_momentum_impulse",
    "impulse": "physical_sciences_momentum_impulse",
    "collisions": "physical_sciences_momentum_impulse",
    "conservation of momentum": "physical_sciences_momentum_impulse",
    "1d momentum": "physical_sciences_momentum_impulse",
    "elastic and inelastic collisions": "physical_sciences_momentum_impulse",
    "impulse-momentum theorem": "physical_sciences_momentum_impulse",
    "chemical equilibrium": "physical_sciences_chemistry_equilibrium",
    "equilibrium and stoichiometry": "physical_sciences_chemistry_equilibrium",
    "stoichiometry": "physical_sciences_chemistry_equilibrium",
    "genetics": "life_sciences_genetics",
    "life sciences": "life_sciences_genetics",
    "genetics and inheritance": "life_sciences_genetics",
    "genetics & inheritance": "life_sciences_genetics",
    "monohybrid cross": "life_sciences_genetics",
    "punnett square": "life_sciences_genetics",
    "dihybrid cross": "life_sciences_dihybrid_cross",
    "dihybrid": "life_sciences_dihybrid_cross",
    "pedigree diagram": "life_sciences_pedigree",
    "pedigree": "life_sciences_pedigree",
    "meiosis": "life_sciences_genetics",
    "finance and tax": "mathematical_literacy_finance_tax",
    "mathematical literacy": "mathematical_literacy_finance_tax",
    "taxation": "mathematical_literacy_finance_tax",
    "income tax": "mathematical_literacy_finance_tax",
    "sars tax": "mathematical_literacy_finance_tax",
    "paye": "mathematical_literacy_finance_tax",
    "maps and scales": "mathematical_literacy_maps_scales",
    "map scales": "mathematical_literacy_maps_scales",
    "topographic map": "mathematical_literacy_maps_scales",
    "scale": "mathematical_literacy_maps_scales",
    "travel time": "mathematical_literacy_maps_scales",
    "complex numbers": "technical_mathematics_complex_numbers",
    "technical mathematics": "technical_mathematics_complex_numbers",
    "complex numbers polar": "technical_mathematics_complex_numbers",
    "polar form": "technical_mathematics_complex_numbers",
    "de moivre": "technical_mathematics_complex_numbers",
    "mensuration": "technical_mathematics_mensuration",
    "trapezoidal rule": "technical_mathematics_mensuration",
    "mid-ordinate rule": "technical_mathematics_mensuration",
    "irregular area": "technical_mathematics_mensuration",
    # Natural Sciences aliases
    "electric circuits": "natural_sciences_electric_circuits",
    "circuits": "natural_sciences_electric_circuits",
    "circuit analysis": "natural_sciences_electric_circuits",
    "ohm's law": "natural_sciences_electric_circuits",
    "series and parallel resistors": "natural_sciences_electric_circuits",
    "chemical reactions": "natural_sciences_chemical_reactions",
    "balancing equations": "natural_sciences_chemical_reactions",
    "reactions": "natural_sciences_chemical_reactions",
    "acids and bases": "natural_sciences_chemical_reactions",
    "neutralisation": "natural_sciences_chemical_reactions",
    "manufacturing": "grade12_accounting_cost_accounting",
    "cost accounting": "grade12_accounting_cost_accounting",
    "production cost statement": "grade12_accounting_cost_accounting",
    "analysis and intepretation of financial statements": "grade12_accounting_financial_indicators",
    "analysis and interpretation of financial statements": "grade12_accounting_financial_indicators",
    "polynomials": "grade12_math_functions",

    # Senior Phase Math & Arithmetic Foundation aliases
    "collect organise and summarise data": "grade8_math_data_handling",
    "interpret analyse and report on data": "grade8_math_data_handling",
    "working with whole numbers": "grade8_math_whole_numbers",
    "whole numbers": "grade8_math_whole_numbers",
    "integers": "grade8_math_integers",
    "numeric patterns": "grade8_math_patterns",
    "relationships between variables": "grade8_math_functions",
    "the decimal notation for fractions": "grade9_math_decimal_notation",
    "fractions in decimal notation": "grade9_math_decimal_notation",
    "common fractions": "grade9_math_fractions",
    "graph paper types": "grade8_math_graph_paper_types",

    # EMS Senior Phase aliases
    "cash receipts journal and cash payments journal (sole trader)": "grade9_ems_crj_cpj",
    "credit transactions (creditors 1)": "grade9_ems_creditors_journal",
    "credit transactions (creditors 2)": "grade9_ems_creditors_journal",
    "credit transactions (debtors 1)": "grade9_ems_debtors_journal",
    "credit transactions (debtors 2)": "grade9_ems_debtors_journal",
    "transactions (cash and credit)": "grade9_ems_crj_cpj",
    "cash payments journal for a services business": "grade8_ems_cpj_and_crj",
    "cash receipts journal for a services business 1": "grade8_ems_crj",
    "cash receipts journal for a services business 2": "grade8_ems_crj",
    "general ledger and trial balance of a service business": "grade8_ems_accounting_cycle",
    "levels and functions of management": "grade8_ems_gap",
    "the production process": "grade7_ems_production_process",
    "production process": "grade7_ems_production_process",

    # Business Studies aliases
    "relationships & team performance": "grade10_bs_entrepreneurial_qualities",
    "relationships and team performance": "grade10_bs_entrepreneurial_qualities",
    "self management": "grade10_bs_entrepreneurial_qualities",
    "assessment of enterpreneural qualities in business": "grade10_bs_entrepreneurial_qualities",
    "assessment of entrepreneurial qualities in business": "grade10_bs_entrepreneurial_qualities",
    "citizenship & responsibilities": "grade10_bs_social_responsibility",
    "citizenship and responsibilities": "grade10_bs_social_responsibility",
    "creative thinking & problem solving": "grade10_bs_creative_thinking",
    "creative thinking and problem solving": "grade10_bs_creative_thinking",
    "ethics and professionalism": "grade10_accounting_ethics",
    "stress crisis & change management": "grade11_bs_adapting_to_challenges",
    "stress crisis and change management": "grade11_bs_adapting_to_challenges",
    "team dynamics & conflict management": "grade12_bs_essay",
    "team dynamics and conflict management": "grade12_bs_essay",
    "transformation of a business plan into an action plan": "grade10_bs_business_plans",
    "business sectors & their environments": "grade10_bs_business_sectors",
    "business sectors and their environments": "grade10_bs_business_sectors",
    "human rights inclusivity & environmental issues": "grade10_bs_social_responsibility",
    "human rights inclusivity and environmental issues": "grade10_bs_social_responsibility",
    "investement securities": "grade12_bs_investments_management",
    "presentations & data responses": "grade10_bs_presentation",
    "presentations and data responses": "grade10_bs_presentation",
    "team perfomance assessment and conflict management": "grade12_bs_essay",
    "team performance assessment and conflict management": "grade12_bs_essay",

    # Technical Mathematics aliases
    "circles angles and angular movement": "technical_mathematics_mensuration",
    "circles  angles and angular movement": "technical_mathematics_mensuration",
    "equalities and inequalities": "grade10_math_equations_inequalities",
    "finance and growth": "grade11_math_finance_growth_decay",
    "number systems": "grade10_math_algebraic_expressions",
    "functions and graphs": "grade10_math_functions",
    "logarithms": "grade11_math_exponents_surds",
    "differentiation": "grade12_math_differential_calculus",
    "euclidean geometry proportionality and similarity": "grade11_math_circle_geometry_theorems",
    "integration": "technical_mathematics_mensuration",

    # Mathematical Literacy aliases
    "assembly diagrams floor plans and packaging": "mathematical_literacy_maps_scales",
    "conversions and time": "mathematical_literacy_maps_scales",
    "conversions & time": "mathematical_literacy_maps_scales",
    "financial documents and tariff ystems": "mathematical_literacy_tariffs_tax_brackets",
    "financial documents and tariff systems": "mathematical_literacy_tariffs_tax_brackets",
    "tariffs and tax": "mathematical_literacy_tariffs_tax_brackets",
    "water and electricity tariffs": "mathematical_literacy_tariffs_tax_brackets",
    "measurement of perimeter and area": "grade10_math_measurements",
    "measuring length weight volume and temperature": "grade10_math_measurements",
    "numbers and calculations with numbers": "grade8_math_whole_numbers",
    "patterns relationships and representations": "grade8_math_functions",
    "personal income expenditure and budgets": "mathematical_literacy_tariffs_tax_brackets",
    "area and volume": "grade10_math_measurements",
    "exchange rates": "mathematical_literacy_finance_tax",
    "interest banking and inflation": "mathematical_literacy_finance_tax",
    "interest banking inflation": "mathematical_literacy_finance_tax",
    "plans and other representations": "mathematical_literacy_maps_scales",
    "weight and temperatute": "grade10_math_measurements",
    "measuring weight bmi medicine dosages": "grade10_math_measurements",
    "lengths perimeter area and volume": "grade10_math_measurements",

    # Physical Sciences (Grades 10, 11, 12) aliases
    "electrostatics": "physical_sciences_electrostatics",
    "electromagnetism": "physical_sciences_electromagnetism",
    "coulombs law": "physical_sciences_electrostatics",
    "coulomb's law": "physical_sciences_electrostatics",
    "faradays law": "physical_sciences_electromagnetism",
    "faraday's law": "physical_sciences_electromagnetism",
    "electric field": "physical_sciences_electrostatics",
    "magnetic flux": "physical_sciences_electromagnetism",
    "reaction in aqeuous solution": "natural_sciences_chemical_reactions",
    "the hydrosphere": "grade10_physical_sciences_matter_materials",
    "the particles that substances are made of": "grade10_physical_sciences_matter_materials",
    "classification of matter": "grade10_physical_sciences_matter_materials",
    "physical and chemical changes": "natural_sciences_chemical_reactions",
    "quantitative aspects of chemical change": "physical_sciences_chemistry_equilibrium",
    "representing chemical change": "natural_sciences_chemical_reactions",
    "units of measurement applied": "grade10_physical_sciences_matter_materials",
    "states of matter and the kinetic theory molecular theory": "physical_sciences_ideal_gases_thermal",
    "transverse pulses": "grade10_physical_sciences_waves_sound_light",
    "transverse waves": "grade10_physical_sciences_waves_sound_light",
    "longitudinal waves": "grade10_physical_sciences_waves_sound_light",
    "sound": "grade10_physical_sciences_waves_sound_light",
    "electromagnetic radiation": "grade10_physical_sciences_waves_sound_light",
    "magnetism": "natural_sciences_electric_circuits",
    "the atom": "grade10_physical_sciences_matter_materials",
    "the periodic table": "grade10_physical_sciences_matter_materials",
    "chemical bonding": "grade10_physical_sciences_matter_materials",
    "motion in one dimension": "physical_sciences_mechanics",
    "mechanical energy": "physical_sciences_work_energy_power",
    "vectors in two dimensions": "grade11_physical_sciences_vectors_newton",
    "newton's laws": "grade11_physical_sciences_vectors_newton",
    "the lithosphere": "grade10_physical_sciences_matter_materials",
    "atomic combinations": "grade10_physical_sciences_matter_materials",
    "energy and chemical change": "physical_sciences_electrochemistry",
    "geometrical optics": "physical_sciences_geometrical_optics",
    "units applied": "grade10_physical_sciences_matter_materials",
    "2d and 3d wavefronts": "physical_sciences_geometrical_optics",
    "intermolecular forces": "grade10_physical_sciences_matter_materials",
    "ideal gases": "physical_sciences_ideal_gases_thermal",
    "types of reaction": "natural_sciences_chemical_reactions",
    "vertical projectile motion in one dimension": "grade12_physical_sciences_vertical_projectile",
    "rate and extent of reaction": "physical_sciences_electrochemistry",
    "optical phenomena and properties of matter": "physical_sciences_geometrical_optics",
    "work energy and power": "physical_sciences_work_energy_power",
    "electrochemical reactions": "physical_sciences_electrochemistry",
    "electrodynamics": "natural_sciences_electric_circuits",
    "organic molecules": "natural_sciences_chemical_reactions",
    "the chemical industry": "physical_sciences_chemistry_equilibrium",
    "skills for science": "grade10_physical_sciences_matter_materials",

    # Life Sciences (Grades 10, 11, 12) aliases
    "biospheres to ecosystems": "life_sciences_environmental_population",
    "cells the basic units of life": "life_sciences_genetics",
    "history of life on earth": "life_sciences_environmental_population",
    "introduction to life sciences": "life_sciences_genetics",
    "the chemistry of life": "life_sciences_genetics",
    "biodiversity and classification": "life_sciences_environmental_population",
    "cell division": "life_sciences_meiosis_human_reproduction",
    "plant and animal tissues": "life_sciences_human_organ_systems",
    "support and transport systems in plants": "life_sciences_photosynthesis_respiration",
    "transport systems in animals": "life_sciences_human_organ_systems",
    "support systems in animals": "life_sciences_human_organ_systems",
    "biodiversity and classification of microorganisms": "life_sciences_environmental_population",
    "gaseous exchange": "life_sciences_human_organ_systems",
    "photosynthesis": "life_sciences_photosynthesis_respiration",
    "animal nutrition": "life_sciences_human_organ_systems",
    "biodiversity of plants": "life_sciences_environmental_population",
    "excretion in humans": "life_sciences_human_organ_systems",
    "biodiversity of animals": "life_sciences_environmental_population",
    "cellular respiration": "life_sciences_photosynthesis_respiration",
    "population ecology": "life_sciences_environmental_population",
    "human impact on the environment": "life_sciences_environmental_population",
    "dna the code of life": "life_sciences_genetics",
    "human responses to the environment": "life_sciences_human_organ_systems",
    "reproductive strategies in vertebrates": "life_sciences_meiosis_human_reproduction",
    "evolution by natural selection": "life_sciences_genetics",
    "human evolution": "life_sciences_genetics",
    "plant responses to the environment": "life_sciences_photosynthesis_respiration",
    "the human endocrine system and homeostasis": "life_sciences_human_organ_systems",

    # Natural Sciences (Grades 7, 8, 9) aliases
    "acids bases and neutral substances": "natural_sciences_matter_and_materials",
    "acids bases and the ph value": "natural_sciences_matter_and_materials",
    "biodiversity": "natural_sciences_life_and_living",
    "energy transfer to surroundings": "natural_sciences_energy_and_change",
    "heat energy transfer": "natural_sciences_energy_and_change",
    "heat insulation and energy saving": "natural_sciences_energy_and_change",
    "historical development of astronomy": "natural_sciences_planet_earth_and_beyond",
    "potential and kinetic energy": "natural_sciences_energy_and_change",
    "properties of materials": "natural_sciences_matter_and_materials",
    "relationship of the moon to the earth": "natural_sciences_planet_earth_and_beyond",
    "relationship of the sun to the earth": "natural_sciences_planet_earth_and_beyond",
    "separating mixtures": "natural_sciences_matter_and_materials",
    "sexual reproduction": "natural_sciences_life_and_living",
    "sources of energy": "natural_sciences_energy_and_change",
    "the biosphere": "natural_sciences_life_and_living",
    "the periodic table of elements": "natural_sciences_matter_and_materials",
    "variation": "natural_sciences_life_and_living",
    "atoms": "natural_sciences_matter_and_materials",
    "beyond the solar system": "natural_sciences_planet_earth_and_beyond",
    "energy transfer in electrical systems": "natural_sciences_energy_and_change",
    "interactions and interdependence within the environment": "natural_sciences_life_and_living",
    "looking into space": "natural_sciences_planet_earth_and_beyond",
    "microorganisms": "natural_sciences_life_and_living",
    "particle model of matter": "natural_sciences_matter_and_materials",
    "photosynthesis and respiration": "natural_sciences_life_and_living",
    "static electricity": "natural_sciences_energy_and_change",
    "the solar system": "natural_sciences_planet_earth_and_beyond",
    "visible light": "natural_sciences_energy_and_change",
    "birth life and the death of a star": "natural_sciences_planet_earth_and_beyond",
    "cells as the basic units of life": "natural_sciences_life_and_living",
    "circulatory and respiratory systems": "natural_sciences_life_and_living",
    "compounds": "natural_sciences_matter_and_materials",
    "cost of electrical energy": "natural_sciences_energy_and_change",
    "digestive system": "natural_sciences_life_and_living",
    "electric cells as energy systems": "natural_sciences_electric_circuits",
    "energy and the national electricity grid": "natural_sciences_energy_and_change",
    "forces": "natural_sciences_energy_and_change",
    "mining of mineral resources": "natural_sciences_planet_earth_and_beyond",
    "resistance": "natural_sciences_electric_circuits",
    "safety with electricity": "natural_sciences_energy_and_change",
    "systems in the human body": "natural_sciences_life_and_living",
    "the atmosphere": "natural_sciences_planet_earth_and_beyond",
    "the earth as a system": "natural_sciences_planet_earth_and_beyond",
    "glossary1": "natural_sciences_matter_and_materials",
    "glossary2": "natural_sciences_matter_and_materials",
    "glossary3": "natural_sciences_matter_and_materials",
    "glossary4": "natural_sciences_matter_and_materials",
    "graphs": "grade8_math_functions",
    "geometric studio": "grade10_math_euclidean_geometry",
    "probability studio": "grade12_math_counting_probability",
    "organic molecules": "grade12_physical_sciences_organic_chemistry",
    "organic chemistry": "grade12_physical_sciences_organic_chemistry",
    "acids and bases": "grade12_physical_sciences_acids_bases",
    "electrodynamics": "grade12_physical_sciences_electrodynamics",
    "optical phenomena and properties of matter": "grade12_physical_sciences_optical_phenomena",
    "photoelectric effect": "grade12_physical_sciences_optical_phenomena",
    "circles angles and angular movement": "technical_mathematics_circles_angles",
    "circles  angles and angular movement": "technical_mathematics_circles_angles",
}

