"""
Session File Writer & Dual-Layer Audit Pipeline (Phase D1)
Implements Complete-App-Implementation-Plan.md §1:
1. Layer 1: Compute-ready Firestore document in `session_index/{sessionId}`.
2. Layer 2: Machine-readable YAML Frontmatter + Markdown audit file in Firebase Storage.
"""

import os
import yaml
from datetime import datetime
from typing import Dict, Any, Optional
from pathlib import Path


def build_session_markdown(session_data: Dict[str, Any]) -> str:
    """
    Assembles a dual-format YAML Frontmatter + Markdown audit document.
    Enables instant YAML parsing for AI agents and clean human readability for audits.
    """
    session_id = session_data.get("sessionId", f"session_{int(datetime.utcnow().timestamp())}")
    user_id = session_data.get("userId", "anonymous_student")
    subject = session_data.get("subject", "Mathematics")
    grade = str(session_data.get("grade", "10"))
    topic = session_data.get("topic", "General Topic")
    subskill = session_data.get("subskill", "Core Concepts")
    score = float(session_data.get("score", 0.0))
    duration_sec = int(session_data.get("durationSeconds", 0))
    misconceptions = session_data.get("misconceptionTags", [])
    procedure_steps = session_data.get("procedureSteps", [])
    cell_errors = session_data.get("cellErrors", [])
    timestamp_str = session_data.get("timestamp", datetime.utcnow().isoformat())

    frontmatter = {
        "sessionId": session_id,
        "userId": user_id,
        "subject": subject,
        "grade": grade,
        "topic": topic,
        "subskill": subskill,
        "timestamp": timestamp_str,
        "durationSeconds": duration_sec,
        "score": score,
        "misconceptionTags": misconceptions,
        "totalStepsMarked": len(procedure_steps),
        "cellErrorsCount": len(cell_errors)
    }

    yaml_header = yaml.dump(frontmatter, default_flow_style=False, sort_keys=False)

    # Markdown body for human inspection & dispute audit
    body_md = f"""# Fundile Session Audit Trail

- **Session ID:** `{session_id}`
- **Learner ID:** `{user_id}`
- **Subject & Grade:** {subject} Grade {grade}
- **Topic:** {topic} ({subskill})
- **Completion Date:** {timestamp_str}
- **Recorded Duration:** {duration_sec}s
- **Final Awarded Score:** {round(score * 100, 1)}%

---

## 1. Procedure & Step Evaluations

| Step # | Description | Status | Marks Earned |
|---|---|---|---|
"""
    if procedure_steps:
        for idx, step in enumerate(procedure_steps, start=1):
            s_desc = step.get("desc", f"Transition Step {idx}")
            s_stat = "✓ Correct" if step.get("correct", False) else "✗ Incorrect"
            s_marks = step.get("marks", 1)
            body_md += f"| {idx} | {s_desc} | {s_stat} | {s_marks} |\n"
    else:
        body_md += "| 1 | Standard Problem Set Submission | Completed | Full Marks |\n"

    body_md += "\n---\n\n## 2. Diagnosed Misconception Tags\n\n"
    if misconceptions:
        for tag in misconceptions:
            body_md += f"- `{tag}`: Identified conceptual bottleneck.\n"
    else:
        body_md += "- None diagnosed. Learner demonstrated canonical procedural mastery.\n"

    body_md += "\n---\n*Audit record generated by Fundile Autonomous Engine. Immutable.*"

    return f"---\n{yaml_header}---\n\n{body_md}\n"


def write_session_audit(
    session_data: Dict[str, Any],
    firestore_client=None,
    storage_bucket=None,
    local_backup_dir: Optional[str] = None
) -> Dict[str, Any]:
    """
    Writes session record to:
    1. Firestore `session_index/{sessionId}` (compute-ready JSON document).
    2. Firebase Storage `sessions/{userId}/{year}/{month}/{sessionId}.md` (YAML+Markdown file).
    3. Optional local directory fallback for development/offline testing.
    """
    session_id = session_data.get("sessionId", f"session_{int(datetime.utcnow().timestamp())}")
    user_id = session_data.get("userId", "anonymous_student")
    now = datetime.utcnow()
    year_str = now.strftime("%Y")
    month_str = now.strftime("%m")
    
    storage_path = f"sessions/{user_id}/{year_str}/{month_str}/{session_id}.md"
    markdown_content = build_session_markdown(session_data)

    # 1. Firestore Write: session_index/{sessionId}
    firestore_written = False
    if firestore_client:
        try:
            doc_ref = firestore_client.collection("session_index").document(session_id)
            doc_ref.set({
                "sessionId": session_id,
                "userId": user_id,
                "subject": session_data.get("subject", "Mathematics"),
                "grade": str(session_data.get("grade", "10")),
                "topic": session_data.get("topic", "General Topic"),
                "subskill": session_data.get("subskill", "Core Concepts"),
                "score": float(session_data.get("score", 0.0)),
                "durationSeconds": int(session_data.get("durationSeconds", 0)),
                "misconceptionTags": session_data.get("misconceptionTags", []),
                "procedureSteps": session_data.get("procedureSteps", []),
                "cellErrors": session_data.get("cellErrors", []),
                "timestamp": session_data.get("timestamp", now.isoformat()),
                "mdStoragePath": storage_path,
                "createdAt": now
            })
            firestore_written = True

            # Update StudentModel mastery model
            try:
                from app.services.student_model import StudentModel
                model = StudentModel(firestore_client)
                model.record_submission(
                    user_id=user_id,
                    subject=session_data.get("subject", "Mathematics"),
                    grade=str(session_data.get("grade", "10")),
                    topic=session_data.get("topic", "General Topic"),
                    subskill=session_data.get("subskill", "Core Concepts"),
                    score=float(session_data.get("score", 0.0)),
                    max_score=1.0,
                    metadata={
                        "durationSeconds": int(session_data.get("durationSeconds", 0)),
                        "misconceptionTags": session_data.get("misconceptionTags", []),
                        "sessionId": session_id,
                    }
                )
            except Exception as sm_err:
                print(f"[AUDIT WARNING] StudentModel update failed: {sm_err}")
        except Exception as e:
            print(f"[AUDIT WARNING] Firestore session_index write failed: {e}")

    # 2. Firebase Storage Write
    storage_written = False
    if storage_bucket:
        try:
            blob = storage_bucket.blob(storage_path)
            blob.upload_from_string(markdown_content, content_type="text/markdown")
            storage_written = True
        except Exception as e:
            print(f"[AUDIT WARNING] Storage markdown upload failed: {e}")

    # 3. Local disk fallback (guarantees zero data loss in offline/local environments)
    if not storage_written:
        target_dir = Path(local_backup_dir or "caps-ai-backend/storage_sessions") / user_id / year_str / month_str
        target_dir.mkdir(parents=True, exist_ok=True)
        file_path = target_dir / f"{session_id}.md"
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(markdown_content)
        storage_written = True
        storage_path = str(file_path)

    return {
        "status": "success",
        "sessionId": session_id,
        "firestore_indexed": firestore_written,
        "mdStoragePath": storage_path,
        "timestamp": now.isoformat()
    }
