import { 
  ClipboardList, 
  Calculator, 
  BookOpen, 
  Briefcase, 
  FlaskConical, 
  Dna, 
  Cpu, 
  Coins, 
  Leaf
} from 'lucide-react';
import { getSubjectTheme } from '../../theme/subjectPalette';

export const SUBJECT_TABS_CONFIG = [
  {
    id: 'desk',
    name: "Today's Desk",
    shortName: 'Desk',
    icon: ClipboardList,
    accentColor: getSubjectTheme('desk').base,
    theme: getSubjectTheme('desk'),
    badge: '2 Due',
    badgeColor: 'bg-rose-500 text-white shadow-sm shadow-rose-500/40',
    grades: [7, 8, 9, 10, 11, 12],
    isDesk: true,
  },
  {
    id: 'accounting',
    name: 'Accounting',
    shortName: 'Accounting',
    icon: BookOpen,
    accentColor: getSubjectTheme('accounting').base,
    theme: getSubjectTheme('accounting'),
    badge: '84%',
    badgeColor: 'bg-emerald-600 text-white shadow-sm shadow-emerald-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    shortName: 'Maths',
    icon: Calculator,
    accentColor: getSubjectTheme('mathematics').base,
    theme: getSubjectTheme('mathematics'),
    badge: '82%',
    badgeColor: 'bg-purple-600 text-white shadow-sm shadow-purple-500/40',
    grades: [7, 8, 9, 10, 11, 12],
  },
  {
    id: 'physical_sciences',
    name: 'Physical Sciences',
    shortName: 'Physics',
    icon: FlaskConical,
    accentColor: getSubjectTheme('physical_sciences').base,
    theme: getSubjectTheme('physical_sciences'),
    badge: '68%',
    badgeColor: 'bg-teal-600 text-white shadow-sm shadow-teal-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'business_studies',
    name: 'Business Studies',
    shortName: 'Business',
    icon: Briefcase,
    accentColor: getSubjectTheme('business_studies').base,
    theme: getSubjectTheme('business_studies'),
    badge: '75%',
    badgeColor: 'bg-rose-600 text-white shadow-sm shadow-rose-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'life_sciences',
    name: 'Life Sciences',
    shortName: 'Life Sci',
    icon: Dna,
    accentColor: getSubjectTheme('life_sciences').base,
    theme: getSubjectTheme('life_sciences'),
    badge: '80%',
    badgeColor: 'bg-lime-700 text-white shadow-sm shadow-lime-700/40',
    grades: [10, 11, 12],
  },
  {
    id: 'technical_mathematics',
    name: 'Technical Mathematics',
    shortName: 'Tech Maths',
    icon: Cpu,
    accentColor: getSubjectTheme('technical_mathematics').base,
    theme: getSubjectTheme('technical_mathematics'),
    badge: '70%',
    badgeColor: 'bg-slate-600 text-white shadow-sm shadow-slate-600/40',
    grades: [10, 11, 12],
  },
  {
    id: 'mathematical_literacy',
    name: 'Mathematical Literacy',
    shortName: 'Maths Lit',
    icon: Calculator,
    accentColor: getSubjectTheme('mathematical_literacy').base,
    theme: getSubjectTheme('mathematical_literacy'),
    badge: '78%',
    badgeColor: 'bg-fuchsia-600 text-white shadow-sm shadow-fuchsia-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'ems',
    name: 'EMS',
    shortName: 'EMS',
    icon: Coins,
    accentColor: getSubjectTheme('ems').base,
    theme: getSubjectTheme('ems'),
    badge: '80%',
    badgeColor: 'bg-orange-700 text-white shadow-sm shadow-orange-700/40',
    grades: [7, 8, 9],
  },
  {
    id: 'natural_sciences',
    name: 'Natural Sciences',
    shortName: 'Nat Sci',
    icon: Leaf,
    accentColor: getSubjectTheme('natural_sciences').base,
    theme: getSubjectTheme('natural_sciences'),
    badge: '75%',
    badgeColor: 'bg-cyan-700 text-white shadow-sm shadow-cyan-700/40',
    grades: [7, 8, 9],
  }
];
