import { 
  ClipboardList, 
  Calculator, 
  BookOpen, 
  Briefcase, 
  FlaskConical, 
  Dna, 
  Cpu, 
  Coins, 
  Leaf
} from 'lucide-react';

export const SUBJECT_TABS_CONFIG = [
  {
    id: 'desk',
    name: "Today's Desk",
    shortName: 'Desk',
    icon: ClipboardList,
    accentColor: '#13519C',
    badge: '2 Due',
    badgeColor: 'bg-rose-500 text-white shadow-sm shadow-rose-500/40',
    grades: [7, 8, 9, 10, 11, 12],
    isDesk: true,
  },
  {
    id: 'accounting',
    name: 'Accounting',
    shortName: 'Accounting',
    icon: BookOpen,
    accentColor: '#059669',
    badge: '84%',
    badgeColor: 'bg-emerald-600 text-white shadow-sm shadow-emerald-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    shortName: 'Maths',
    icon: Calculator,
    accentColor: '#2563EB',
    badge: '82%',
    badgeColor: 'bg-blue-600 text-white shadow-sm shadow-blue-500/40',
    grades: [7, 8, 9, 10, 11, 12],
  },
  {
    id: 'physical_sciences',
    name: 'Physical Sciences',
    shortName: 'Physics',
    icon: FlaskConical,
    accentColor: '#0891B2',
    badge: '68%',
    badgeColor: 'bg-cyan-600 text-white shadow-sm shadow-cyan-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'business_studies',
    name: 'Business Studies',
    shortName: 'Business',
    icon: Briefcase,
    accentColor: '#EA580C',
    badge: '75%',
    badgeColor: 'bg-[#FF9100] text-white shadow-sm shadow-orange-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'life_sciences',
    name: 'Life Sciences',
    shortName: 'Life Sci',
    icon: Dna,
    accentColor: '#0D9488',
    badge: '80%',
    badgeColor: 'bg-teal-600 text-white shadow-sm shadow-teal-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'technical_mathematics',
    name: 'Technical Mathematics',
    shortName: 'Tech Maths',
    icon: Cpu,
    accentColor: '#7C3AED',
    badge: '70%',
    badgeColor: 'bg-indigo-600 text-white shadow-sm shadow-indigo-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'mathematical_literacy',
    name: 'Mathematical Literacy',
    shortName: 'Maths Lit',
    icon: Calculator,
    accentColor: '#8B5CF6',
    badge: '78%',
    badgeColor: 'bg-purple-600 text-white shadow-sm shadow-purple-500/40',
    grades: [10, 11, 12],
  },
  {
    id: 'ems',
    name: 'EMS',
    shortName: 'EMS',
    icon: Coins,
    accentColor: '#D97706',
    badge: '80%',
    badgeColor: 'bg-amber-600 text-white shadow-sm shadow-amber-500/40',
    grades: [7, 8, 9],
  },
  {
    id: 'natural_sciences',
    name: 'Natural Sciences',
    shortName: 'Nat Sci',
    icon: Leaf,
    accentColor: '#059669',
    badge: '75%',
    badgeColor: 'bg-emerald-600 text-white shadow-sm shadow-emerald-500/40',
    grades: [7, 8, 9],
  }
];
