from flask import Blueprint
 
math_bp = Blueprint('math', __name__)
 
from . import routes
from . import whole_numbers_routes
from . import exponents_routes
from . import geometry_construction_routes
from . import geometry_2d_shapes_routes
from . import geometry_straight_lines_routes
from . import grade8_whole_numbers_routes
from . import grade8_integers_routes
from . import grade8_exponents_routes
from . import grade8_patterns_routes
from . import grade8_functions_routes
from . import grade8_algebraic_expressions_routes
from . import grade8_algebraic_equations_routes
from . import grade9_whole_numbers_routes
from . import grade9_integers_routes
from . import grade9_fractions_routes
from . import grade9_exponents_routes
from . import grade9_decimal_notation_routes
from . import grade9_patterns_routes
from . import grade9_functions_relationships_routes
from . import grade9_algebraic_expressions_routes
from . import grade9_algebraic_equations_routes
from . import grade10_algebraic_expressions_routes
from . import grade10_exponents_routes
from . import grade10_patterns_sequences_routes
from . import grade10_equations_inequalities_routes
from . import grade10_trigonometry1_routes
from . import grade11_exponents_surds_routes
from . import grade11_equations_inequalities_routes
from . import grade11_patterns_sequences_routes
from . import grade11_analytical_geometry_routes
from . import grade12_patterns_sequences_series_routes
from . import grade12_functions_routes
from . import grade12_finance_routes
from . import grade12_trigonometry_routes
