import React from 'react';
import TopicModeCard from './TopicModeCard';
import {
    isGrade10BSMicroEnvironment,
    isGrade10BSBusinessFunctions,
    isGrade10BSMarketEnvironment,
    isGrade10BSMacroEnvironment,
    isGrade10BSInterrelationship,
    isGrade10BSBusinessSectors,
    isGrade10BSSocioEconomic,
    isGrade10BSSocialResponsibility,
    isGrade10BSEntrepreneurial,
    isGrade10BSFormsOfOwnership,
    isGrade10BSConceptOfQuality,
    isGrade10BSCreativeThinking,
    isGrade10BSBusinessOpportunities,
    isGrade10BSBusinessLocation,
    isGrade10BSContracts,
    isGrade10BSPresentation,
    isGrade10BSBusinessPlans,
    isGrade11BSInfluences,
    isGrade11BSChallenges,
    isGrade11BSAdapting,
    isGrade11BSContemporarySocioEconomic,
    isGrade11BSBusinessSectors,
    isGrade11BSBenefitsOfCompany,
    isGrade11BSAvenues,
    isGrade11BSCreativeThinking,
    isGrade11BSStressCrisisChange,
    isGrade11BSMarketingFunction,
    isGrade11BSProductionFunction,
    isGrade11BSProfessionalismEthics,
    isGrade11BSEntrepreneurialAssessment,
    isGrade11BSCitizenship,
    isGrade11BSBusinessPlanTransformation,
    isGrade11BSStartBusinessVenture,
    isGrade11BSPresentationOfInformation,
    isGrade12BSCreativeThinking,
    isGrade12BSEthicsProfessionalism,
    isGrade12BSMacroEnvironmentStrategies,
    isGrade12BSImpactOfLegislation,
    isGrade12BSHumanResourcesFunction,
    isGrade12BSBusinessSectorsEnvironments,
    isGrade12BSQualityOfPerformance,
    isGrade12BSManagementLeadership,
    isGrade12BSInvestmentSecurities,
    isGrade12BSInvestmentInsurance,
    isGrade12BSTeamPerformanceConflict,
    isGrade12BSHumanRightsInclusivity,
    isGrade12BSSocialResponsibilityCsr,
    isGrade12BSPresentationDataResponses,
    isGrade12BSFormsOfOwnershipSuccess,
} from '../topicMatchers';

const BusinessStudiesTopicModeCards = ({ selectedTopic, selectedTopicDisplayName, getTopicTerm, navigateToWorkspaceWithMode, flags }) => {
    const topicName = selectedTopic?.name;
    if (!topicName) return null;

    const cards = [
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSMicroEnvironment(topicName),
            title: 'Topic 1: Micro Environment',
            description: 'Term 1. Internal environment of the business, Vision/Mission/Goals/Objectives, Organisational culture & resources, Eight business functions, and levels/tasks of management.',
            scaffoldMode: 'grade10_bs_micro_environment_scaffold',
            scaffoldLabel: 'Micro Environment • Scaffold',
            practiceMode: 'grade10_bs_micro_environment_practice',
            practiceLabel: 'Micro Environment • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSBusinessFunctions(topicName),
            title: 'Topic 2: Business Functions',
            description: 'Term 1. Focus on General Management, Administration, Financial, Purchasing, and Public Relations. Understanding the roles and differences between management and leadership.',
            scaffoldMode: 'grade10_bs_business_functions_scaffold',
            scaffoldLabel: 'Business functions • Scaffold',
            practiceMode: 'grade10_bs_business_functions_practice',
            practiceLabel: 'Business functions • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSMarketEnvironment(topicName),
            title: 'Topic 3: Market Environment',
            description: 'Term 1. External forces directly affecting the business. Consumers, suppliers, intermediaries, competitors, civil society, NGOs, CBOs, and regulators.',
            scaffoldMode: 'grade10_bs_market_environment_scaffold',
            scaffoldLabel: 'Market Environment • Scaffold',
            practiceMode: 'grade10_bs_market_environment_practice',
            practiceLabel: 'Market Environment • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSMacroEnvironment(topicName),
            title: 'Topic 4: Macro Environment',
            description: 'Term 1. External forces beyond business control. PESTLE analysis (Political, Economic, Social, Technological, Legal, Environmental).',
            scaffoldMode: 'grade10_bs_macro_environment_scaffold',
            scaffoldLabel: 'Macro Environment • Scaffold',
            practiceMode: 'grade10_bs_macro_environment_practice',
            practiceLabel: 'Macro Environment • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSInterrelationship(topicName),
            title: 'Topic 5: Interrelationship of Environments',
            description: 'Term 1. How micro, market and macro environments interact and influence each other.',
            scaffoldMode: 'grade10_bs_interrelationship_scaffold',
            scaffoldLabel: 'Interrelationship of environments • Scaffold',
            practiceMode: 'grade10_bs_interrelationship_practice',
            practiceLabel: 'Interrelationship of environments • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSBusinessSectors(topicName),
            title: 'Topic 6: Business Sectors',
            description: 'Term 1. Primary, Secondary and Tertiary sectors. Formal vs informal sectors, and public vs private sectors.',
            scaffoldMode: 'grade10_bs_business_sectors_scaffold',
            scaffoldLabel: 'Business sectors • Scaffold',
            practiceMode: 'grade10_bs_business_sectors_practice',
            practiceLabel: 'Business sectors • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSSocioEconomic(topicName),
            title: 'Topic 7: Socio-economic Issues',
            description: 'Term 2. Poverty, inequality, inclusivity, unemployment, HIV/Aids, gambling, piracy, counterfeiting, strikes, violence, and crime.',
            scaffoldMode: 'grade10_bs_socio_economic_issues_scaffold',
            scaffoldLabel: 'Socio-economic Issues • Scaffold',
            practiceMode: 'grade10_bs_socio_economic_issues_practice',
            practiceLabel: 'Socio-economic Issues • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSSocialResponsibility(topicName),
            title: 'Topic 8: Social Responsibility',
            description: 'Term 2. Initiatives businesses take to improve the well-being of the community and environment. CSI projects.',
            scaffoldMode: 'grade10_bs_social_responsibility_scaffold',
            scaffoldLabel: 'Social responsibility • Scaffold',
            practiceMode: 'grade10_bs_social_responsibility_practice',
            practiceLabel: 'Social responsibility • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSEntrepreneurial(topicName),
            title: 'Topic 9: Entrepreneurial Qualities',
            description: 'Term 2. Key characteristics of successful entrepreneurs, identifying business opportunities, and assessing feasibility.',
            scaffoldMode: 'grade10_bs_entrepreneurial_qualities_scaffold',
            scaffoldLabel: 'Entrepreneurial qualities • Scaffold',
            practiceMode: 'grade10_bs_entrepreneurial_qualities_practice',
            practiceLabel: 'Entrepreneurial qualities • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSFormsOfOwnership(topicName),
            title: 'Topic 10: Forms of Ownership',
            description: 'Term 2. Sole traders, partnerships, close corporations, companies (private, public, personal liability, state-owned), and cooperatives.',
            scaffoldMode: 'grade10_bs_forms_of_ownership_scaffold',
            scaffoldLabel: 'Forms of Ownership • Scaffold',
            practiceMode: 'grade10_bs_forms_of_ownership_practice',
            practiceLabel: 'Forms of Ownership • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSConceptOfQuality(topicName),
            title: 'Topic 11: Concept of Quality',
            description: 'Term 2. Quality control vs quality assurance, SABS, ISO, and total quality management (TQM).',
            scaffoldMode: 'grade10_bs_concept_of_quality_scaffold',
            scaffoldLabel: 'Concept of Quality • Scaffold',
            practiceMode: 'grade10_bs_concept_of_quality_practice',
            practiceLabel: 'Concept of Quality • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSCreativeThinking(topicName),
            title: 'Topic 12: Creative Thinking & Problem Solving',
            description: 'Term 3. The meaning of creative thinking and problem solving, problem-solving techniques (brainstorming, mind-mapping, Delphi, SCAMPER, force-field), and the benefits of creative thinking to a business.',
            scaffoldMode: 'grade10_bs_creative_thinking_scaffold',
            scaffoldLabel: 'Creative Thinking • Scaffold',
            practiceMode: 'grade10_bs_creative_thinking_practice',
            practiceLabel: 'Creative Thinking • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSBusinessOpportunities(topicName),
            title: 'Topic 13: Business Opportunities',
            description: 'Term 3. Meaning of a business opportunity, assessing needs and desires, designing research instruments, market research protocol, internal vs external research, and SWOT analysis.',
            scaffoldMode: 'grade10_bs_business_opportunities_scaffold',
            scaffoldLabel: 'Business Opportunities • Scaffold',
            practiceMode: 'grade10_bs_business_opportunities_practice',
            practiceLabel: 'Business Opportunities • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSBusinessLocation(topicName),
            title: 'Topic 14: Business Location Decisions',
            description: 'Term 3. The importance of business location and the factors impacting where a business is located (market, labour, suppliers, transport, costs, legislation).',
            scaffoldMode: 'grade10_bs_business_location_scaffold',
            scaffoldLabel: 'Business Location • Scaffold',
            practiceMode: 'grade10_bs_business_location_practice',
            practiceLabel: 'Business Location • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSContracts(topicName),
            title: 'Topic 15: Contracts',
            description: 'Term 3. Meaning of a contract, parties and types of contracts, legal requirements for a valid contract, and termination of contracts.',
            scaffoldMode: 'grade10_bs_contracts_scaffold',
            scaffoldLabel: 'Contracts • Scaffold',
            practiceMode: 'grade10_bs_contracts_practice',
            practiceLabel: 'Contracts • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSPresentation(topicName),
            title: 'Topic 16: Presentation of Business Information',
            description: 'Term 3. Business reports, the importance/advantages/disadvantages of visual aids, and factors to consider when preparing verbal presentations.',
            scaffoldMode: 'grade10_bs_presentation_scaffold',
            scaffoldLabel: 'Presentation • Scaffold',
            practiceMode: 'grade10_bs_presentation_practice',
            practiceLabel: 'Presentation • Practice',
        },
        {
            condition: flags.isGrade10BusinessStudies && isGrade10BSBusinessPlans(topicName),
            title: 'Topic 17: Understanding Business Plans',
            description: 'Term 3. The importance and components of a business plan, PESTLE analysis, vision/mission/goals/objectives, legal requirements, and strategies to overcome competition.',
            scaffoldMode: 'grade10_bs_business_plans_scaffold',
            scaffoldLabel: 'Business Plans • Scaffold',
            practiceMode: 'grade10_bs_business_plans_practice',
            practiceLabel: 'Business Plans • Practice',
        },
        {
            condition: flags.isGrade11BusinessStudies && (isGrade11BSInfluences(topicName) || isGrade11BSChallenges(topicName)),
            title: selectedTopicDisplayName,
            description: `${getTopicTerm(topicName)}. Choose a mode to begin. Scaffold follows the guided step sequence for concepts, application, and discussion with hints and memo comparison. Practice lets you choose a subskill or use mixed practice for a marked review flow.`,
            scaffoldMode: isGrade11BSInfluences(topicName)
                ? 'grade11_bs_influences_on_business_environments_scaffold'
                : 'grade11_bs_challenges_of_the_business_environments_scaffold',
            scaffoldLabel: `${selectedTopicDisplayName} • Scaffold`,
            practiceMode: isGrade11BSInfluences(topicName)
                ? 'grade11_bs_influences_on_business_environments_practice'
                : 'grade11_bs_challenges_of_the_business_environments_practice',
            practiceLabel: `${selectedTopicDisplayName} • Practice`,
        },
        ...[
            { match: isGrade11BSAdapting, prefix: 'grade11_bs_adapting_to_challenges', title: 'Adapting to Challenges', term: 'Term 1' },
            { match: isGrade11BSContemporarySocioEconomic, prefix: 'grade11_bs_socio_economic_issues', title: 'Contemporary Socio-economic Issues', term: 'Term 1' },
            { match: isGrade11BSBenefitsOfCompany, prefix: 'grade11_bs_benefits_of_a_company', title: 'Benefits of a Company', term: 'Term 1' },
            { match: isGrade11BSAvenues, prefix: 'grade11_bs_avenues_of_acquiring_businesses', title: 'Avenues of Acquiring Businesses', term: 'Term 1' },
            { match: isGrade11BSBusinessSectors, prefix: 'grade11_bs_business_sectors', title: 'Business Sectors', term: 'Term 1' },
            { match: isGrade11BSCreativeThinking, prefix: 'grade11_bs_creative_thinking', title: 'Creative Thinking & Problem Solving', term: 'Term 2' },
            { match: isGrade11BSStressCrisisChange, prefix: 'grade11_bs_stress_crisis_change', title: 'Stress, Crisis & Change Management', term: 'Term 2' },
            { match: isGrade11BSMarketingFunction, prefix: 'grade11_bs_marketing_function', title: 'The Marketing Function', term: 'Term 2' },
            { match: isGrade11BSProductionFunction, prefix: 'grade11_bs_production_function', title: 'The Production Function', term: 'Term 2' },
            { match: isGrade11BSProfessionalismEthics, prefix: 'grade11_bs_professionalism_and_ethics', title: 'Professionalism & Ethics', term: 'Term 2' },
            { match: isGrade11BSEntrepreneurialAssessment, prefix: 'grade11_bs_entrepreneurial_assessment', title: 'Assessment of Entrepreneurial Qualities', term: 'Term 3' },
            { match: isGrade11BSCitizenship, prefix: 'grade11_bs_citizenship_responsibilities', title: 'Citizenship & Responsibilities', term: 'Term 3' },
            { match: isGrade11BSBusinessPlanTransformation, prefix: 'grade11_bs_business_plan_transformation', title: 'Business Plan into an Action Plan', term: 'Term 3' },
            { match: isGrade11BSStartBusinessVenture, prefix: 'grade11_bs_start_business_venture', title: 'Starting a Business Venture', term: 'Term 3' },
            { match: isGrade11BSPresentationOfInformation, prefix: 'grade11_bs_presentation_of_information', title: 'Presentation of Business Information', term: 'Term 3' },
        ].map((t) => ({
            condition: flags.isGrade11BusinessStudies && t.match(topicName),
            title: t.title,
            description: `${t.term}. Choose a mode to begin. Scaffold follows the guided step sequence for concepts, application, and discussion with hints and memo comparison. Practice lets you choose a subskill or use mixed practice for a marked review flow.`,
            scaffoldMode: `${t.prefix}_scaffold`,
            scaffoldLabel: `${t.title} • Scaffold`,
            practiceMode: `${t.prefix}_practice`,
            practiceLabel: `${t.title} • Practice`,
        })),
        ...[
            { match: isGrade12BSImpactOfLegislation, prefix: 'grade12_bs_impact_of_legislation', title: 'Impact of Recent Legislation', term: 'Term 1' },
            { match: isGrade12BSHumanResourcesFunction, prefix: 'grade12_bs_human_resources_function', title: 'Human Resources Function', term: 'Term 1' },
            { match: isGrade12BSCreativeThinking, prefix: 'grade12_bs_creative_thinking_problem_solving', title: 'Creative Thinking & Problem Solving', term: 'Term 1' },
            { match: isGrade12BSEthicsProfessionalism, prefix: 'grade12_bs_ethics_and_professionalism', title: 'Ethics & Professionalism', term: 'Term 1' },
            { match: isGrade12BSMacroEnvironmentStrategies, prefix: 'grade12_bs_macro_environment_strategies', title: 'Macro Environment: Business Strategies', term: 'Term 1' },
            { match: isGrade12BSBusinessSectorsEnvironments, prefix: 'grade12_bs_business_sectors_environments', title: 'Business Sectors & their Environments', term: 'Term 2' },
            { match: isGrade12BSQualityOfPerformance, prefix: 'grade12_bs_quality_of_performance', title: 'Quality of Performance', term: 'Term 2' },
            { match: isGrade12BSManagementLeadership, prefix: 'grade12_bs_management_and_leadership', title: 'Management & Leadership', term: 'Term 2' },
            { match: isGrade12BSInvestmentSecurities, prefix: 'grade12_bs_investment_securities', title: 'Investment: Securities', term: 'Term 2' },
            { match: isGrade12BSInvestmentInsurance, prefix: 'grade12_bs_investment_insurance', title: 'Investment: Insurance', term: 'Term 2' },
            { match: isGrade12BSTeamPerformanceConflict, prefix: 'grade12_bs_team_performance_conflict', title: 'Team Performance & Conflict Management', term: 'Term 2' },
            { match: isGrade12BSHumanRightsInclusivity, prefix: 'grade12_bs_human_rights_inclusivity', title: 'Human Rights, Inclusivity & Environment', term: 'Term 3' },
            { match: isGrade12BSSocialResponsibilityCsr, prefix: 'grade12_bs_social_responsibility_csr_csi', title: 'Social Responsibility & Corporate Citizenship', term: 'Term 3' },
            { match: isGrade12BSPresentationDataResponses, prefix: 'grade12_bs_presentation_data_responses', title: 'Presentation & Data Responses', term: 'Term 3' },
            { match: isGrade12BSFormsOfOwnershipSuccess, prefix: 'grade12_bs_forms_of_ownership_success', title: 'Forms of Ownership: Success & Failure', term: 'Term 3' },
        ].map((t) => ({
            condition: flags.isGrade12BusinessStudies && t.match(topicName),
            title: t.title,
            description: `${t.term}. Choose a mode to begin. Scaffold follows the guided step sequence for concepts, application, and discussion with hints and memo comparison. Practice lets you choose a subskill or use mixed practice for a marked review flow.`,
            scaffoldMode: `${t.prefix}_scaffold`,
            scaffoldLabel: `${t.title} • Scaffold`,
            practiceMode: `${t.prefix}_practice`,
            practiceLabel: `${t.title} • Practice`,
        })),
    ];

    const card = cards.find((entry) => entry.condition);
    if (!card) return null;

    return (
        <TopicModeCard
            title={card.title}
            description={card.description}
            onStartScaffold={() => navigateToWorkspaceWithMode(card.scaffoldMode, card.scaffoldLabel)}
            onStartPractice={() => navigateToWorkspaceWithMode(card.practiceMode, card.practiceLabel)}
            containerClassName={card.containerClassName}
            titleClassName={card.titleClassName}
            descriptionClassName={card.descriptionClassName}
            scaffoldButtonClassName={card.scaffoldButtonClassName}
            practiceButtonClassName={card.practiceButtonClassName}
        />
    );
};

export default BusinessStudiesTopicModeCards;
