import React from 'react';
import TopicModeCard from './TopicModeCard';
import {
    isWholeNumbersTopic,
    isIntegersTopic,
    isFractionsTopic,
    isDecimalNotationTopic,
    isExponentsTopic,
    isPatternsTopic,
    isPatternsSequencesTopic,
    isPatternsSequencesSeriesTopic,
    isGrade12FunctionsTopic,
    isGrade12FinanceTopic,
    isGrade12TrigonometryTopic,
    isFunctionsRelationshipsTopic,
    isAlgebraicExpressionsTopic,
    isAlgebraicEquationsTopic,
    isEquationsInequalitiesTopic,
    isTrigonometry1Topic,
    isGrade10FunctionsTopic,
    isExponentsSurdsTopic,
    isAnalyticalGeometryTopic,
    isGeoConstructionTopic,
    isGeo2DShapesTopic,
    isGeoStraightLinesTopic,
} from '../topicMatchers';

const filledGreenPracticeButton = 'px-4 py-2 bg-green-600 text-white rounded-lg font-semibold hover:bg-green-700';

const MathTopicModeCards = ({ selectedTopic, navigateToWorkspaceWithMode, flags }) => {
    const topicName = selectedTopic?.name;
    if (!topicName) return null;

    const cards = [
        {
            condition: flags.isGrade12Math && isPatternsSequencesSeriesTopic(topicName),
            title: '1 Sequences and series',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers arithmetic & geometric sequences, sigma notation, arithmetic series and geometric series.',
            scaffoldMode: 'grade12_patterns_sequences_series_scaffold',
            scaffoldLabel: 'Sequences and series • Scaffold',
            practiceMode: 'grade12_patterns_sequences_series_practice',
            practiceLabel: 'Sequences and series • Practice',
        },
        {
            condition: flags.isGrade12Math && isGrade12FunctionsTopic(topicName),
            title: '2 Functions',
            description: 'Term 1. Inverses, intercepts & domain/range ideas, exponential-log conversions, logarithmic laws and change of base.',
            scaffoldMode: 'grade12_functions_scaffold',
            scaffoldLabel: 'Functions • Scaffold',
            practiceMode: 'grade12_functions_practice',
            practiceLabel: 'Functions • Practice',
        },
        {
            condition: flags.isGrade12Math && isGrade12FinanceTopic(topicName),
            title: '3 Finance',
            description: 'Term 1. Solve for n using logarithms, nominal vs effective rates, future value annuities, and payment calculations.',
            scaffoldMode: 'grade12_finance_scaffold',
            scaffoldLabel: 'Finance • Scaffold',
            practiceMode: 'grade12_finance_practice',
            practiceLabel: 'Finance • Practice',
        },
        {
            condition: flags.isGrade12Math && isGrade12TrigonometryTopic(topicName),
            title: '4 Trigonometry',
            description: 'Term 1. Reduction formulae, exact values, identities and compound angles.',
            scaffoldMode: 'grade12_trigonometry_scaffold',
            scaffoldLabel: 'Trigonometry • Scaffold',
            practiceMode: 'grade12_trigonometry_practice',
            practiceLabel: 'Trigonometry • Practice',
        },
        {
            condition: flags.isGrade7Math && isWholeNumbersTopic(topicName),
            title: 'Whole Numbers',
            description: 'Scaffold builds method step-by-step (no calculator). Practice reinforces with mixed question types.',
            scaffoldMode: 'grade7_whole_scaffold',
            scaffoldLabel: 'Whole Numbers • Scaffold',
            practiceMode: 'grade7_whole_practice',
            practiceLabel: 'Whole Numbers • Practice',
        },
        {
            condition: flags.isGrade8Math && isWholeNumbersTopic(topicName),
            title: '1. Whole Numbers',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator).',
            scaffoldMode: 'grade8_whole_scaffold',
            scaffoldLabel: 'Whole Numbers • Scaffold',
            practiceMode: 'grade8_whole_practice',
            practiceLabel: 'Whole Numbers • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade8Math && isIntegersTopic(topicName),
            title: '2. Integers',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator).',
            scaffoldMode: 'grade8_integers_scaffold',
            scaffoldLabel: 'Integers • Scaffold',
            practiceMode: 'grade8_integers_practice',
            practiceLabel: 'Integers • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade8Math && isExponentsTopic(topicName),
            title: '3. Exponents',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator).',
            scaffoldMode: 'grade8_exponents_scaffold',
            scaffoldLabel: 'Exponents • Scaffold',
            practiceMode: 'grade8_exponents_practice',
            practiceLabel: 'Exponents • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade8Math && isPatternsTopic(topicName),
            title: '4. Numeric and geometric patterns',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator).',
            scaffoldMode: 'grade8_patterns_scaffold',
            scaffoldLabel: 'Numeric & geometric patterns • Scaffold',
            practiceMode: 'grade8_patterns_practice',
            practiceLabel: 'Numeric & geometric patterns • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade8Math && isFunctionsRelationshipsTopic(topicName),
            title: '5. Functions and relationships 1',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions.',
            scaffoldMode: 'grade8_functions_1_scaffold',
            scaffoldLabel: 'Functions & relationships 1 • Scaffold',
            practiceMode: 'grade8_functions_1_practice',
            practiceLabel: 'Functions & relationships 1 • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade8Math && isAlgebraicExpressionsTopic(topicName),
            title: '6. Algebraic expressions 1',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions.',
            scaffoldMode: 'grade8_algebraic_expressions_1_scaffold',
            scaffoldLabel: 'Algebraic expressions 1 • Scaffold',
            practiceMode: 'grade8_algebraic_expressions_1_practice',
            practiceLabel: 'Algebraic expressions 1 • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade8Math && isAlgebraicEquationsTopic(topicName),
            title: '7. Algebraic equations 1',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions.',
            scaffoldMode: 'grade8_algebraic_equations_1_scaffold',
            scaffoldLabel: 'Algebraic equations 1 • Scaffold',
            practiceMode: 'grade8_algebraic_equations_1_practice',
            practiceLabel: 'Algebraic equations 1 • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isWholeNumbersTopic(topicName),
            title: '1. Whole Numbers',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator). CSV renders as tables; long division uses ASCII layout.',
            scaffoldMode: 'grade9_whole_scaffold',
            scaffoldLabel: 'Whole Numbers • Scaffold',
            practiceMode: 'grade9_whole_practice',
            practiceLabel: 'Whole Numbers • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isIntegersTopic(topicName),
            title: '2. Integers',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator). Includes properties table questions (CSV rendered as table).',
            scaffoldMode: 'grade9_integers_scaffold',
            scaffoldLabel: 'Integers • Scaffold',
            practiceMode: 'grade9_integers_practice',
            practiceLabel: 'Integers • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isFractionsTopic(topicName),
            title: '3. Fractions',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator). Includes equivalent fractions, simplifying, mixed numbers, and add/subtract with common denominators.',
            scaffoldMode: 'grade9_fractions_scaffold',
            scaffoldLabel: 'Fractions • Scaffold',
            practiceMode: 'grade9_fractions_practice',
            practiceLabel: 'Fractions • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isDecimalNotationTopic(topicName),
            title: '4. Decimal Notation',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator). Includes converting between fractions, decimals and percentages, and calculations with decimals.',
            scaffoldMode: 'grade9_decimal_notation_scaffold',
            scaffoldLabel: 'Decimal Notation • Scaffold',
            practiceMode: 'grade9_decimal_notation_practice',
            practiceLabel: 'Decimal Notation • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isExponentsTopic(topicName),
            title: '5. Exponents',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator). Includes exponent laws (table), order of operations, zero and negative exponents.',
            scaffoldMode: 'grade9_exponents_scaffold',
            scaffoldLabel: 'Exponents • Scaffold',
            practiceMode: 'grade9_exponents_practice',
            practiceLabel: 'Exponents • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isPatternsTopic(topicName),
            title: '6. Numeric and geometric patterns',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions (no calculator). Includes arithmetic/geometric sequences, square numbers, and changing differences.',
            scaffoldMode: 'grade9_patterns_scaffold',
            scaffoldLabel: 'Numeric & geometric patterns • Scaffold',
            practiceMode: 'grade9_patterns_practice',
            practiceLabel: 'Numeric & geometric patterns • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isFunctionsRelationshipsTopic(topicName),
            title: '7. Functions and relationships 1',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Includes flow diagrams, tables, formulae and graph reading.',
            scaffoldMode: 'grade9_functions_relationships_1_scaffold',
            scaffoldLabel: 'Functions and relationships 1 • Scaffold',
            practiceMode: 'grade9_functions_relationships_1_practice',
            practiceLabel: 'Functions and relationships 1 • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isAlgebraicExpressionsTopic(topicName),
            title: '8. Algebraic expressions 1',
            description: 'Next topic. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers simplifying, like terms, substitution, and expression building (Term 1 scope).',
            scaffoldMode: 'grade9_algebraic_expressions_1_scaffold',
            scaffoldLabel: 'Algebraic expressions 1 • Scaffold',
            practiceMode: 'grade9_algebraic_expressions_1_practice',
            practiceLabel: 'Algebraic expressions 1 • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade9Math && isAlgebraicEquationsTopic(topicName),
            title: '9. Algebraic equations 1',
            description: 'Next topic. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers inspection, inverse operations, solving linear equations (including brackets), and setting up equations from situations (Term 1 scope).',
            scaffoldMode: 'grade9_algebraic_equations_1_scaffold',
            scaffoldLabel: 'Algebraic equations 1 • Scaffold',
            practiceMode: 'grade9_algebraic_equations_1_practice',
            practiceLabel: 'Algebraic equations 1 • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade10Math && isAlgebraicExpressionsTopic(topicName),
            title: '1. Algebraic expressions',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers real number system, rounding, surds estimation, expanding, and factorisation.',
            scaffoldMode: 'grade10_algebraic_expressions_scaffold',
            scaffoldLabel: 'Algebraic expressions • Scaffold',
            practiceMode: 'grade10_algebraic_expressions_practice',
            practiceLabel: 'Algebraic expressions • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade10Math && isExponentsTopic(topicName),
            title: '2. Exponents',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers laws of exponents, zero/negative exponents, rational exponents, and simplification strategies.',
            scaffoldMode: 'grade10_exponents_scaffold',
            scaffoldLabel: 'Exponents • Scaffold',
            practiceMode: 'grade10_exponents_practice',
            practiceLabel: 'Exponents • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade10Math && isPatternsSequencesTopic(topicName),
            title: '3 Patterns and sequences',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers arithmetic and geometric patterns, nth term T_n, and linear patterns from situations.',
            scaffoldMode: 'grade10_patterns_sequences_scaffold',
            scaffoldLabel: 'Patterns and sequences • Scaffold',
            practiceMode: 'grade10_patterns_sequences_practice',
            practiceLabel: 'Patterns and sequences • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade10Math && isEquationsInequalitiesTopic(topicName),
            title: '4 Equations and inequalities',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers linear equations, solving by factorisation, simultaneous equations, literal equations, and linear inequalities.',
            scaffoldMode: 'grade10_equations_inequalities_scaffold',
            scaffoldLabel: 'Equations and inequalities • Scaffold',
            practiceMode: 'grade10_equations_inequalities_practice',
            practiceLabel: 'Equations and inequalities • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade10Math && isTrigonometry1Topic(topicName),
            title: '5 Trigonometry 1',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step (includes calculator procedure); Practice gives varied questions. Covers trig ratios in right-angled triangles, special angles, and solving for sides/angles using inverse trig.',
            scaffoldMode: 'grade10_trigonometry_1_scaffold',
            scaffoldLabel: 'Trigonometry 1 • Scaffold',
            practiceMode: 'grade10_trigonometry_1_practice',
            practiceLabel: 'Trigonometry 1 • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade10Math && isGrade10FunctionsTopic(topicName),
            title: '6 Functions',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers function notation, domain & range, linear/quadratic/hyperbola/exponential and trig graphs, and an interactive grapher to manipulate the parameters a and q.',
            scaffoldMode: 'grade10_functions_scaffold',
            scaffoldLabel: 'Functions • Scaffold',
            practiceMode: 'grade10_functions_practice',
            practiceLabel: 'Functions • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade11Math && isExponentsSurdsTopic(topicName),
            title: '1 Exponents and surds',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers laws of exponents, rational exponents, surds, rationalising denominators, and applications of exponentials.',
            scaffoldMode: 'grade11_exponents_surds_scaffold',
            scaffoldLabel: 'Exponents and surds • Scaffold',
            practiceMode: 'grade11_exponents_surds_practice',
            practiceLabel: 'Exponents and surds • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade11Math && isEquationsInequalitiesTopic(topicName),
            title: '2 Equations and inequalities',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers solving quadratic equations and inequalities (including completing the square and quadratic formula) and simultaneous equations.',
            scaffoldMode: 'grade11_equations_inequalities_scaffold',
            scaffoldLabel: 'Equations and inequalities • Scaffold',
            practiceMode: 'grade11_equations_inequalities_practice',
            practiceLabel: 'Equations and inequalities • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade11Math && isPatternsSequencesTopic(topicName),
            title: '3 Patterns and sequences',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers arithmetic & quadratic sequences, differences, and nth term T_n.',
            scaffoldMode: 'grade11_patterns_sequences_scaffold',
            scaffoldLabel: 'Patterns and sequences • Scaffold',
            practiceMode: 'grade11_patterns_sequences_practice',
            practiceLabel: 'Patterns and sequences • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade11Math && isAnalyticalGeometryTopic(topicName),
            title: '4 Analytical geometry',
            description: 'Term 1. Choose a mode to begin. Scaffold builds method step-by-step; Practice gives varied questions. Covers distance, midpoint, gradients, equations of straight lines, and parallel/perpendicular lines.',
            scaffoldMode: 'grade11_analytical_geometry_scaffold',
            scaffoldLabel: 'Analytical geometry • Scaffold',
            practiceMode: 'grade11_analytical_geometry_practice',
            practiceLabel: 'Analytical geometry • Practice',
            practiceButtonClassName: filledGreenPracticeButton,
        },
        {
            condition: flags.isGrade7Math && isExponentsTopic(topicName),
            title: 'Exponents',
            description: 'Scaffold builds method step-by-step (no calculator). Practice reinforces with mixed question types.',
            scaffoldMode: 'grade7_exponents_scaffold',
            scaffoldLabel: 'Exponents • Scaffold',
            practiceMode: 'grade7_exponents_practice',
            practiceLabel: 'Exponents • Practice',
        },
        {
            condition: flags.isGrade7Math && isGeoConstructionTopic(topicName),
            title: 'Construction of Geometric Figures',
            description: 'Scaffold builds method step-by-step (no calculator). Practice reinforces with mixed question types.',
            scaffoldMode: 'grade7_geo_construct_scaffold',
            scaffoldLabel: 'Construction of Geometric Figures • Scaffold',
            practiceMode: 'grade7_geo_construct_practice',
            practiceLabel: 'Construction of Geometric Figures • Practice',
        },
        {
            condition: flags.isGrade7Math && isGeo2DShapesTopic(topicName),
            title: 'Geometry of 2D shapes',
            description: 'Scaffold builds method step-by-step (no calculator). Practice reinforces with mixed question types.',
            scaffoldMode: 'grade7_geo2d_scaffold',
            scaffoldLabel: 'Geometry of 2D shapes • Scaffold',
            practiceMode: 'grade7_geo2d_practice',
            practiceLabel: 'Geometry of 2D shapes • Practice',
        },
        {
            condition: flags.isGrade7Math && isGeoStraightLinesTopic(topicName),
            title: 'Geometry of straight lines',
            description: 'Scaffold builds method step-by-step (no calculator). Practice reinforces with mixed question types.',
            scaffoldMode: 'grade7_straight_lines_scaffold',
            scaffoldLabel: 'Geometry of straight lines • Scaffold',
            practiceMode: 'grade7_straight_lines_practice',
            practiceLabel: 'Geometry of straight lines • Practice',
        },
    ];

    const card = cards.find((entry) => entry.condition);
    if (!card) return null;

    return (
        <TopicModeCard
            title={card.title}
            description={card.description}
            onStartScaffold={() => navigateToWorkspaceWithMode(card.scaffoldMode, card.scaffoldLabel)}
            onStartPractice={() => navigateToWorkspaceWithMode(card.practiceMode, card.practiceLabel)}
            practiceButtonClassName={card.practiceButtonClassName}
        />
    );
};

export default MathTopicModeCards;
