// This file is auto-generated by the build_curriculum_data.py script.
// Do not edit this file manually.

export const curriculumData = {
    "Accounting": {
        "10": {
            "topics": [
                "Accounting principles",
                "Analysis and Interpretation of financial statements of a sole trader",
                "Budgeting",
                "Cost accounting",
                "Difference between financial and managerial accounting",
                "Ethics",
                "Financial Information and GAAP",
                "Financial accounting of a sole trader",
                "Financial accounts and year end adjustments of a sole trader",
                "Financial statements of a sole trader",
                "Informal or indigenous bookkeeping systems",
                "Internal control",
                "Managing Resources",
                "Salaries and wages journal",
                "Value Added Tax"
            ],
            "syllabus_info": true
        },
        "11": {
            "topics": [
                "Analysis and Interpretation of financial statements",
                "Bank Reconciliation",
                "Bank reconciliation",
                "Budgeting",
                "Calculations involving percentages",
                "Cash Budget Variance Analysis",
                "Cash flow statement",
                "Control accounts",
                "Cost accounting Manufacturing",
                "Debtors age analysis",
                "Disposal of tangible assets",
                "Ethics",
                "Fixed Tangible Assets",
                "Internal Control",
                "Introduction to accounting",
                "Inventory systems",
                "Non profit Organisations or Clubs",
                "Partnerships",
                "Partnerships Analysis of financial statements",
                "The accounting equation",
                "Value added tax"
            ],
            "syllabus_info": true
        },
        "12": {
            "topics": [
                "Analysis and Interpretation of financial statements",
                "Bank reconciliation",
                "Basic concepts of accounting",
                "Budgets",
                "Calculations involving percentages",
                "Cash Budget Variance Analysis",
                "Cash flow statement",
                "Companies",
                "Control accounts",
                "Debtors age analysis",
                "Disposal of tangible assets",
                "Fixed Assets",
                "Inventories",
                "Manufacturing",
                "Preliminary information",
                "Reconciliations",
                "The accounting equation",
                "Value Added Tax",
                "Value added tax"
            ],
            "syllabus_info": true
        }
    },
    "Business Studies": {
        "10": {
            "topics": [
                "Micro environment",
                "Business functions",
                "The market environment",
                "The macro environment",
                "Interrelationship of environments",
                "Business sectors",
                "Socio-economic issues",
                "Social responsibility",
                "Entrepreneurial qualities",
                "Forms of ownership",
                "The concept of quality"
            ],
            "syllabus_info": true
        },
        "11": {
            "topics": [
                "Influences on business environments",
                "The challenges of the business environments",
                "Adapting to the challenges in the business environments",
                "Contemporary socio-economic issues and businesses",
                "Business sectors",
                "Benefits of a company over other forms of ownership",
                "Avenues of acquiring businesses",
                "Creative thinking and problem solving",
                "Stress, crisis and change management",
                "The marketing function",
                "The production function",
                "Professionalism and ethics"
            ],
            "syllabus_info": true
        },
        "12": {
            "topics": [
                "Ethics and professionalism",
                "Impact of recent legislation on businesses",
                "Investement Securities",
                "Investments Insurance",
                "Macro environment Business strategies",
                "Quality of performance",
                "Team perfomance assessment and conflict management",
                "The human resources function"
            ],
            "syllabus_info": true
        }
    },
    "Economic and Management Sciences": {
        "7": {
            "topics": [
                "Accounting concepts",
                "Budgets",
                "Businesses",
                "Goods and Service",
                "History of money",
                "Income and Expenses",
                "Inequality and poverty",
                "Needs and Wants",
                "Savings",
                "Starting a business",
                "The entrepreneur",
                "The production process"
            ],
            "syllabus_info": true
        },
        "8": {
            "topics": [
                "Accounting concepts",
                "Cash payments journal for a services business",
                "Cash receipts journal for a services business 1",
                "Cash receipts journal for a services business 2",
                "Factors of production",
                "Forms of ownership",
                "General ledger and Trial balance of a service business",
                "Government",
                "Levels and functions of management",
                "Source documents",
                "The National Budget",
                "The markets",
                "the accounting cycle"
            ],
            "syllabus_info": true
        },
        "9": {
            "topics": [
                "Business Plan",
                "Economic systems",
                "Functions of a business",
                "Sectors of the economy",
                "The Price Theory",
                "The circular flow",
                "Trade Unions"
            ],
            "syllabus_info": true
        }
    },
    "Mathematical Literacy": {
        "10": {
            "topics": [
                "Assembly diagrams floor plans and packaging",
                "Banking interest and taxation",
                "Conversions and time",
                "Data handling",
                "Financial documents and tariff ystems",
                "Measurement of perimeter and area",
                "Measuring length weight volume and temperature",
                "Numbers and calculations with numbers",
                "Patterns relationships and representations",
                "Personal income expenditure and budgets",
                "Probability",
                "Scale maps and plans"
            ],
            "syllabus_info": true
        },
        "11": {
            "topics": [
                "Area and Volume",
                "CONVERSIONS AND TIME",
                "DATA HANDLING",
                "EXCHANGE RATES",
                "Financial documents and tariff systems",
                "Interest banking and inflation",
                "MAPS",
                "PATTERNS RELATIONSHIPS AND REPRESENTATIONS",
                "PLANS AND OTHER REPRESENTATIONS",
                "Probability",
                "Weight and Temperatute"
            ],
            "syllabus_info": true
        },
        "12": {
            "topics": [
                "Data handling",
                "Financial documents and tariff systems",
                "Income tax",
                "Measuring weight BMI medicine dosages",
                "Probability",
                "exchange rates",
                "interest banking inflation",
                "lengths perimeter area and volume",
                "plans and scale",
                "scale and map work"
            ],
            "syllabus_info": true
        }
    },
    "Mathematics": {
        "10": {
            "topics": [
                "Algebraic expressions",
                "Analytical geometry",
                "Equations and inequalities",
                "Euclidean geometry 1",
                "Euclidean geometry 2",
                "Exponents",
                "Finance and growth",
                "Functions",
                "Measurements",
                "Number patterns",
                "Probability",
                "Statistics",
                "Trigonometry 1",
                "Trigonometry 2"
            ],
            "syllabus_info": true
        },
        "11": {
            "topics": [
                "Analytical geometry",
                "Equations and inequalities",
                "Euclidean geometry",
                "Exponents and surds",
                "Finance growth and decay",
                "Functions",
                "Linear programming",
                "Measurement",
                "Number patterns",
                "Probability",
                "Statistics",
                "Trigonometry"
            ],
            "syllabus_info": true
        },
        "12": {
            "topics": [
                "Analytical geometry",
                "Differential calculus",
                "Euclidean geometry",
                "Finance",
                "Functions",
                "Polynomials",
                "Probability",
                "Sequences and series",
                "Statistics",
                "Trigonometry"
            ],
            "syllabus_info": true
        },
        "7": {
            "topics": [
                "Algebraic equations 1",
                "Algebraic equations 2",
                "Algebraic expressions 1",
                "Algebraic expressions 2",
                "Collect organise and summarise data",
                "Construction of geometric figures",
                "Exponents",
                "Fractions",
                "Functions and relationships 1",
                "Functions and relationships 2",
                "Geometry of 2D shapes",
                "Geometry of 3D objects",
                "Geometry of straight lines",
                "Graphs",
                "Integers",
                "Interpret analyse and report on data",
                "Numeric and geometric patterns",
                "Numeric patterns",
                "Perimeter and area of 2D shapes",
                "Probability",
                "Relationships between variables",
                "Represent data",
                "Surface area and volume of 3D objects",
                "The decimal notation for fractions",
                "Transformation geometry",
                "Working with whole numbers"
            ],
            "syllabus_info": true
        },
        "8": {
            "topics": [
                "Algebraic equations",
                "Algebraic equations 1",
                "Algebraic equations 2",
                "Algebraic expressions 1",
                "Algebraic expressions 2",
                "Collect organise and summarise data",
                "Common fractions",
                "Construction of geometric figures",
                "Exponents",
                "Fractions in decimal notation",
                "Functions and relationships 1",
                "Functions and relationships 2",
                "Geometry of 2D shapes",
                "Geometry of 3D objects",
                "Geometry of straight lines",
                "Graphs",
                "Integers",
                "Interpret analyse and report on data",
                "Numeric and geometric patterns",
                "Perimeter and area of 2D shapes",
                "Probability",
                "Represent data",
                "Surface area and volume of 3D objects",
                "The theorem of Pythagoras",
                "Transformation geometry",
                "Whole numbers"
            ],
            "syllabus_info": true
        },
        "9": {
            "topics": [
                "Algebraic expressions 1",
                "Algebraic expressions 2",
                "Area and perimeter of 2D shapes",
                "Collect organise and summarise data",
                "Construction of geometric figures",
                "Equations 1",
                "Equations 2",
                "Exponents",
                "Fractions",
                "Functions",
                "Functions and relationships",
                "Geometry of 2D shapes",
                "Geometry of 3D objects",
                "Geometry of straight lines",
                "Graphs",
                "Integers",
                "Interpret analyse and report on data",
                "Patterns",
                "Probability",
                "Pythagoras Theorem",
                "Representing data",
                "Surface area volume and capacity of 3D objects",
                "The decimal notation for fractions",
                "Transformation geometry",
                "Whole numbers"
            ],
            "syllabus_info": true
        }
    },
    "Physical Sciences": {
        "10": {
            "topics": [
                "Chemical bonding",
                "Chemical equations",
                "Classification of matter",
                "Electric circuits",
                "Electromagnetic radiation",
                "Electrostatics",
                "Longitudinal waves",
                "Magnetism",
                "Mechanical energy",
                "Motion in one dimension",
                "Physical and Chemical Changes",
                "Quantitative aspects of chemical change",
                "Reaction in aqeuous solution",
                "Skills for science",
                "Sound",
                "States of matter and the kinetic theory molecular theory",
                "The atom",
                "The hydrosphere",
                "The particles that substances are made of",
                "The periodic table",
                "Transverse pulses",
                "Transverse waves",
                "Units of measurement applied",
                "Vectors and scalars"
            ],
            "syllabus_info": true
        },
        "11": {
            "topics": [
                "2D and 3D wavefronts",
                "Atomic combinations",
                "Electric circuits",
                "Electromagnetism",
                "Electrostatics",
                "Energy and chemical change",
                "Geometrical optics",
                "Ideal gases",
                "Intermolecular forces",
                "Quantitative aspects of chemical change",
                "The lithosphere",
                "Types of reaction",
                "Units applied",
                "Vectors in two dimensions"
            ],
            "syllabus_info": true
        },
        "12": {
            "topics": [
                "Acids and bases",
                "Chemical equilibrium",
                "Electric circuits",
                "Electrochemical reactions",
                "Electrodynamics",
                "Momentum and Impulse",
                "Optical phenomena and properties of matter",
                "Organic molecules",
                "Rate and Extent of Reaction",
                "Skills for science",
                "The Doppler effect",
                "The chemical industry",
                "Vertical projectile motion in one dimension",
                "Work energy and power"
            ],
            "syllabus_info": true
        }
    },
    "Technical Mathematics": {
        "10": {
            "topics": [
                "Algebraic expressions",
                "Analytical Geometry",
                "Circles  angles and angular Movement",
                "Equalities and inequalities",
                "Exponents",
                "Finance and Growth",
                "Functions and graphs",
                "Geometry",
                "Introduction",
                "Number Systems",
                "Trigonometry"
            ],
            "syllabus_info": true
        },
        "11": {
            "topics": [
                "Analytical geometry",
                "Circles angles and angular movement",
                "Equations",
                "Euclidean geometry",
                "Exponents and surds",
                "Finance growth and decays",
                "Functions and graphs",
                "Logarithms",
                "Mensuration",
                "Trigonometry"
            ],
            "syllabus_info": true
        },
        "12": {
            "topics": [
                "Analytical geometry",
                "Complex numbers",
                "Differentiation",
                "Euclidean Geometry Proportionality and similarity",
                "Financial mathematics",
                "Integration",
                "Polynomials",
                "Trigonometry"
            ],
            "syllabus_info": true
        }
    }
};